allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  esbuild: true
  puppeteer: true
  vue-demi: true
catalog:
  rollup: 4.62.4
overrides:
  minimatch: 10.2.6
  rollup: 'catalog:'
  basic-ftp: 6.2.0
  serialize-javascript: 7.1.0
  flatted: 3.4.4
  ip-address: 10.5.0
  postcss: 8.5.26
  tmp: 0.2.7
  esbuild: 0.28.2
  form-data: 4.0.6
  markdown-it: 15.0.0
  launch-editor: 2.14.1
  '@babel/core': 8.0.1
  js-yaml@4: 5.2.3
  fast-uri@3: 3.1.5
publicHoistPattern:
  - '*eslint*'
