/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[[auth]]/get-password-reset': RouteRecordInfo<'/[[auth]]/get-password-reset', '/:auth?/get-password-reset', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    '/[[auth]]/login': RouteRecordInfo<'/[[auth]]/login', '/:auth?/login', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    '/[[auth]]/password-reset': RouteRecordInfo<'/[[auth]]/password-reset', '/:auth?/password-reset', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    '/[[auth]]/register': RouteRecordInfo<'/[[auth]]/register', '/:auth?/register', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    '/[[...path]]+': RouteRecordInfo<'/[[...path]]+', '/:path(.*)*', { path?: ParamValueZeroOrMore<true> }, { path?: ParamValueZeroOrMore<false> }>,
    'home': RouteRecordInfo<'home', '/(home)', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/auth/openid/[provider]': RouteRecordInfo<'/auth/openid/[provider]', '/auth/openid/:provider', { provider: ParamValue<true> }, { provider: ParamValue<false> }>,
    '/filters/[projectId]/settings/delete': RouteRecordInfo<'/filters/[projectId]/settings/delete', '/filters/:projectId/settings/delete', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/filters/[projectId]/settings/edit': RouteRecordInfo<'/filters/[projectId]/settings/edit', '/filters/:projectId/settings/edit', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/filters/new': RouteRecordInfo<'/filters/new', '/filters/new', Record<never, never>, Record<never, never>>,
    '/labels/(labels)': RouteRecordInfo<'/labels/(labels)', '/labels/(labels)', Record<never, never>, Record<never, never>>,
    '/labels/new': RouteRecordInfo<'/labels/new', '/labels/new', Record<never, never>, Record<never, never>>,
    '/migrate/[service]': RouteRecordInfo<'/migrate/[service]', '/migrate/:service', { service: ParamValue<true> }, { service: ParamValue<false> }>,
    '/projects/[[parentProjectId]]/new': RouteRecordInfo<'/projects/[[parentProjectId]]/new', '/projects/:parentProjectId?/new', { parentProjectId?: ParamValueZeroOrOne<true> }, { parentProjectId?: ParamValueZeroOrOne<false> }>,
    '/projects/[projectId]/[[viewId]]': RouteRecordInfo<'/projects/[projectId]/[[viewId]]', '/projects/:projectId/:viewId?', { projectId: ParamValue<true>, viewId?: ParamValueZeroOrOne<true> }, { projectId: ParamValue<false>, viewId?: ParamValueZeroOrOne<false> }>,
    '/projects/[projectId]/info': RouteRecordInfo<'/projects/[projectId]/info', '/projects/:projectId/info', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/archive': RouteRecordInfo<'/projects/[projectId]/settings/archive', '/projects/:projectId/settings/archive', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/background': RouteRecordInfo<'/projects/[projectId]/settings/background', '/projects/:projectId/settings/background', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/delete': RouteRecordInfo<'/projects/[projectId]/settings/delete', '/projects/:projectId/settings/delete', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/duplicate': RouteRecordInfo<'/projects/[projectId]/settings/duplicate', '/projects/:projectId/settings/duplicate', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/edit': RouteRecordInfo<'/projects/[projectId]/settings/edit', '/projects/:projectId/settings/edit', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/share': RouteRecordInfo<'/projects/[projectId]/settings/share', '/projects/:projectId/settings/share', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/views': RouteRecordInfo<'/projects/[projectId]/settings/views', '/projects/:projectId/settings/views', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/settings/webhooks': RouteRecordInfo<'/projects/[projectId]/settings/webhooks', '/projects/:projectId/settings/webhooks', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/(projects)': RouteRecordInfo<'/projects/(projects)', '/projects/(projects)', Record<never, never>, Record<never, never>>,
    '/share/[share]/auth': RouteRecordInfo<'/share/[share]/auth', '/share/:share/auth', { share: ParamValue<true> }, { share: ParamValue<false> }>,
    '/task/[id]': RouteRecordInfo<'/task/[id]', '/task/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/teams/[id]/edit': RouteRecordInfo<'/teams/[id]/edit', '/teams/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/teams/(teams)': RouteRecordInfo<'/teams/(teams)', '/teams/(teams)', Record<never, never>, Record<never, never>>,
    '/teams/new': RouteRecordInfo<'/teams/new', '/teams/new', Record<never, never>, Record<never, never>>,
    '/user/export/download': RouteRecordInfo<'/user/export/download', '/user/export/download', Record<never, never>, Record<never, never>>,
    '/user/settings': RouteRecordInfo<'/user/settings', '/user/settings', Record<never, never>, Record<never, never>>,
    '/user/settings/api-tokens': RouteRecordInfo<'/user/settings/api-tokens', '/user/settings/api-tokens', Record<never, never>, Record<never, never>>,
    '/user/settings/avatar': RouteRecordInfo<'/user/settings/avatar', '/user/settings/avatar', Record<never, never>, Record<never, never>>,
    '/user/settings/caldav': RouteRecordInfo<'/user/settings/caldav', '/user/settings/caldav', Record<never, never>, Record<never, never>>,
    '/user/settings/data-export': RouteRecordInfo<'/user/settings/data-export', '/user/settings/data-export', Record<never, never>, Record<never, never>>,
    '/user/settings/deletion': RouteRecordInfo<'/user/settings/deletion', '/user/settings/deletion', Record<never, never>, Record<never, never>>,
    '/user/settings/email-update': RouteRecordInfo<'/user/settings/email-update', '/user/settings/email-update', Record<never, never>, Record<never, never>>,
    '/user/settings/general': RouteRecordInfo<'/user/settings/general', '/user/settings/general', Record<never, never>, Record<never, never>>,
    '/user/settings/migrate': RouteRecordInfo<'/user/settings/migrate', '/user/settings/migrate', Record<never, never>, Record<never, never>>,
    '/user/settings/password-update': RouteRecordInfo<'/user/settings/password-update', '/user/settings/password-update', Record<never, never>, Record<never, never>>,
    '/user/settings/totp': RouteRecordInfo<'/user/settings/totp', '/user/settings/totp', Record<never, never>, Record<never, never>>,
  }
}
