/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'user.password-reset.request': RouteRecordInfo<'user.password-reset.request', '/:auth?/get-password-reset', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    'user.login': RouteRecordInfo<'user.login', '/:auth?/login', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    'user.password-reset.reset': RouteRecordInfo<'user.password-reset.reset', '/:auth?/password-reset', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    'user.register': RouteRecordInfo<'user.register', '/:auth?/register', { auth?: ParamValueZeroOrOne<true> }, { auth?: ParamValueZeroOrOne<false> }>,
    'not-found': RouteRecordInfo<'not-found', '/:path(.*)*', { path?: ParamValueZeroOrMore<true> }, { path?: ParamValueZeroOrMore<false> }>,
    'home': RouteRecordInfo<'home', '/(home)', Record<never, never>, Record<never, never>>,
    'about': RouteRecordInfo<'about', '/about', Record<never, never>, Record<never, never>>,
    'openid.auth': RouteRecordInfo<'openid.auth', '/auth/openid/:provider', { provider: ParamValue<true> }, { provider: ParamValue<false> }>,
    'filter.settings.delete': RouteRecordInfo<'filter.settings.delete', '/filters/:projectId/settings/delete', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'filter.settings.edit': RouteRecordInfo<'filter.settings.edit', '/filters/:projectId/settings/edit', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'filters.create': RouteRecordInfo<'filters.create', '/filters/new', Record<never, never>, Record<never, never>>,
    'labels.index': RouteRecordInfo<'labels.index', '/labels/(labels)', Record<never, never>, Record<never, never>>,
    'labels.create': RouteRecordInfo<'labels.create', '/labels/new', Record<never, never>, Record<never, never>>,
    'migrate.service': RouteRecordInfo<'migrate.service', '/migrate/:service', { service: ParamValue<true> }, { service: ParamValue<false> }>,
    'project.create': RouteRecordInfo<'project.create', '/projects/:parentProjectId?/new', { parentProjectId?: ParamValueZeroOrOne<true> }, { parentProjectId?: ParamValueZeroOrOne<false> }>,
    '/projects/[projectId]/[[viewId]]': RouteRecordInfo<'/projects/[projectId]/[[viewId]]', '/projects/:projectId/:viewId?', { projectId: ParamValue<true>, viewId?: ParamValueZeroOrOne<true> }, { projectId: ParamValue<false>, viewId?: ParamValueZeroOrOne<false> }>,
    'project.info': RouteRecordInfo<'project.info', '/projects/:projectId/info', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.archive': RouteRecordInfo<'project.settings.archive', '/projects/:projectId/settings/archive', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.background': RouteRecordInfo<'project.settings.background', '/projects/:projectId/settings/background', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.delete': RouteRecordInfo<'project.settings.delete', '/projects/:projectId/settings/delete', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.duplicate': RouteRecordInfo<'project.settings.duplicate', '/projects/:projectId/settings/duplicate', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.edit': RouteRecordInfo<'project.settings.edit', '/projects/:projectId/settings/edit', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.share': RouteRecordInfo<'project.settings.share', '/projects/:projectId/settings/share', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.views': RouteRecordInfo<'project.settings.views', '/projects/:projectId/settings/views', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project.settings.webhooks': RouteRecordInfo<'project.settings.webhooks', '/projects/:projectId/settings/webhooks', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'projects.index': RouteRecordInfo<'projects.index', '/projects/(projects)', Record<never, never>, Record<never, never>>,
    'link-share.auth': RouteRecordInfo<'link-share.auth', '/share/:share/auth', { share: ParamValue<true> }, { share: ParamValue<false> }>,
    'task.detail': RouteRecordInfo<'task.detail', '/task/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'tasks.range': RouteRecordInfo<'tasks.range', '/tasks/by/upcoming', Record<never, never>, Record<never, never>>,
    'teams.edit': RouteRecordInfo<'teams.edit', '/teams/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'teams.index': RouteRecordInfo<'teams.index', '/teams/(teams)', Record<never, never>, Record<never, never>>,
    'teams.create': RouteRecordInfo<'teams.create', '/teams/new', Record<never, never>, Record<never, never>>,
    'user.export.download': RouteRecordInfo<'user.export.download', '/user/export/download', Record<never, never>, Record<never, never>>,
    'user.settings': RouteRecordInfo<'user.settings', '/user/settings', Record<never, never>, Record<never, never>>,
    'user.settings.apiTokens': RouteRecordInfo<'user.settings.apiTokens', '/user/settings/api-tokens', Record<never, never>, Record<never, never>>,
    'user.settings.avatar': RouteRecordInfo<'user.settings.avatar', '/user/settings/avatar', Record<never, never>, Record<never, never>>,
    'user.settings.caldav': RouteRecordInfo<'user.settings.caldav', '/user/settings/caldav', Record<never, never>, Record<never, never>>,
    'user.settings.data-export': RouteRecordInfo<'user.settings.data-export', '/user/settings/data-export', Record<never, never>, Record<never, never>>,
    'user.settings.deletion': RouteRecordInfo<'user.settings.deletion', '/user/settings/deletion', Record<never, never>, Record<never, never>>,
    'user.settings.email-update': RouteRecordInfo<'user.settings.email-update', '/user/settings/email-update', Record<never, never>, Record<never, never>>,
    'user.settings.general': RouteRecordInfo<'user.settings.general', '/user/settings/general', Record<never, never>, Record<never, never>>,
    'migrate.start': RouteRecordInfo<'migrate.start', '/user/settings/migrate', Record<never, never>, Record<never, never>>,
    'user.settings.password-update': RouteRecordInfo<'user.settings.password-update', '/user/settings/password-update', Record<never, never>, Record<never, never>>,
    'user.settings.totp': RouteRecordInfo<'user.settings.totp', '/user/settings/totp', Record<never, never>, Record<never, never>>,
  }
}
