root = "."
tmp_dir = "tmp"

testdata_dir = "testdata"

[build]
  cmd = "/usr/local/go/bin/go build -o ./tmp/vikunja ."
  bin = "./tmp/vikunja"
  args_bin = ["web"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
  exclude_dir = ["frontend", "desktop", "docs", "tmp", "dist", "node_modules", ".git"]
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = "1s"

[log]
  time = true

[misc]
  clean_on_exit = true
