# .air.toml

# The root directory of the project
root = "."
tmp_dir = "tmp"

[build]
# Command to build the application
cmd = "go build -o ./tmp/vikunja ."
# The binary to run
bin = "./tmp/vikunja"
# Watch these directories for changes
include_dir = ["pkg", "rest"]
# Ignore these directories
exclude_dir = ["frontend", "tmp", "dist", "desktop"]

[log]
# Show logs in color
color = true
