
package yaegi_symbols

import (
	"go/constant"
	"go/token"
	"code.vikunja.io/api/pkg/models"
	"reflect"
)

func init() {
	Symbols["code.vikunja.io/api/pkg/models/models"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"APITokenPrefix": reflect.ValueOf(constant.MakeFromLiteral("\"tk_\"", token.STRING, 0)),
			"BucketConfigurationModeFilter": reflect.ValueOf(models.BucketConfigurationModeFilter),
			"BucketConfigurationModeManual": reflect.ValueOf(models.BucketConfigurationModeManual),
			"BucketConfigurationModeNone": reflect.ValueOf(models.BucketConfigurationModeNone),
			"CanDoAPIRoute": reflect.ValueOf(models.CanDoAPIRoute),
			"CollectRoutesForAPITokenUsage": reflect.ValueOf(models.CollectRoutesForAPITokenUsage),
			"CreateDefaultViewsForProject": reflect.ValueOf(models.CreateDefaultViewsForProject),
			"CreateNewProjectForUser": reflect.ValueOf(models.CreateNewProjectForUser),
			"CreateProject": reflect.ValueOf(models.CreateProject),
			"CreateTypesenseCollections": reflect.ValueOf(models.CreateTypesenseCollections),
			"DeleteOrphanedTaskPositions": reflect.ValueOf(models.DeleteOrphanedTaskPositions),
			"DeleteUser": reflect.ValueOf(models.DeleteUser),
			"ErrCodeAPITokenInvalid": reflect.ValueOf(constant.MakeFromLiteral("14001", token.INT, 0)),
			"ErrCodeAttachmentDoesNotBelongToTask": reflect.ValueOf(constant.MakeFromLiteral("4020", token.INT, 0)),
			"ErrCodeBucketDoesNotBelongToProject": reflect.ValueOf(constant.MakeFromLiteral("10002", token.INT, 0)),
			"ErrCodeBucketDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("10001", token.INT, 0)),
			"ErrCodeBucketLimitExceeded": reflect.ValueOf(constant.MakeFromLiteral("10004", token.INT, 0)),
			"ErrCodeBulkTasksMustBeInSameProject": reflect.ValueOf(constant.MakeFromLiteral("4003", token.INT, 0)),
			"ErrCodeBulkTasksNeedAtLeastOne": reflect.ValueOf(constant.MakeFromLiteral("4004", token.INT, 0)),
			"ErrCodeCannotArchiveDefaultProject": reflect.ValueOf(constant.MakeFromLiteral("3013", token.INT, 0)),
			"ErrCodeCannotDeleteDefaultProject": reflect.ValueOf(constant.MakeFromLiteral("3012", token.INT, 0)),
			"ErrCodeCannotDeleteLastTeamMember": reflect.ValueOf(constant.MakeFromLiteral("6006", token.INT, 0)),
			"ErrCodeCannotLeaveExternalTeam": reflect.ValueOf(constant.MakeFromLiteral("6010", token.INT, 0)),
			"ErrCodeCannotRemoveLastBucket": reflect.ValueOf(constant.MakeFromLiteral("10003", token.INT, 0)),
			"ErrCodeIDCannotBeZero": reflect.ValueOf(constant.MakeFromLiteral("2001", token.INT, 0)),
			"ErrCodeInvalidAPITokenPermission": reflect.ValueOf(constant.MakeFromLiteral("14002", token.INT, 0)),
			"ErrCodeInvalidData": reflect.ValueOf(constant.MakeFromLiteral("2002", token.INT, 0)),
			"ErrCodeInvalidFilterExpression": reflect.ValueOf(constant.MakeFromLiteral("4024", token.INT, 0)),
			"ErrCodeInvalidModel": reflect.ValueOf(constant.MakeFromLiteral("2004", token.INT, 0)),
			"ErrCodeInvalidReactionEntityKind": reflect.ValueOf(constant.MakeFromLiteral("4025", token.INT, 0)),
			"ErrCodeInvalidRelationKind": reflect.ValueOf(constant.MakeFromLiteral("4007", token.INT, 0)),
			"ErrCodeInvalidRight": reflect.ValueOf(constant.MakeFromLiteral("9001", token.INT, 0)),
			"ErrCodeInvalidSortOrder": reflect.ValueOf(constant.MakeFromLiteral("4014", token.INT, 0)),
			"ErrCodeInvalidSortParam": reflect.ValueOf(constant.MakeFromLiteral("4013", token.INT, 0)),
			"ErrCodeInvalidTaskColumn": reflect.ValueOf(constant.MakeFromLiteral("4027", token.INT, 0)),
			"ErrCodeInvalidTaskField": reflect.ValueOf(constant.MakeFromLiteral("4016", token.INT, 0)),
			"ErrCodeInvalidTaskFilterComparator": reflect.ValueOf(constant.MakeFromLiteral("4017", token.INT, 0)),
			"ErrCodeInvalidTaskFilterConcatinator": reflect.ValueOf(constant.MakeFromLiteral("4018", token.INT, 0)),
			"ErrCodeInvalidTaskFilterValue": reflect.ValueOf(constant.MakeFromLiteral("4019", token.INT, 0)),
			"ErrCodeInvalidTimezone": reflect.ValueOf(constant.MakeFromLiteral("2003", token.INT, 0)),
			"ErrCodeLabelDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("8002", token.INT, 0)),
			"ErrCodeLabelIsAlreadyOnTask": reflect.ValueOf(constant.MakeFromLiteral("8001", token.INT, 0)),
			"ErrCodeLinkSharePasswordInvalid": reflect.ValueOf(constant.MakeFromLiteral("13002", token.INT, 0)),
			"ErrCodeLinkSharePasswordRequired": reflect.ValueOf(constant.MakeFromLiteral("13001", token.INT, 0)),
			"ErrCodeLinkShareTokenInvalid": reflect.ValueOf(constant.MakeFromLiteral("13003", token.INT, 0)),
			"ErrCodeMustHaveProjectViewToSortByPosition": reflect.ValueOf(constant.MakeFromLiteral("4026", token.INT, 0)),
			"ErrCodeMustProvideUser": reflect.ValueOf(constant.MakeFromLiteral("12003", token.INT, 0)),
			"ErrCodeNeedToHaveProjectReadAccess": reflect.ValueOf(constant.MakeFromLiteral("3004", token.INT, 0)),
			"ErrCodeNeedsFullRecalculation": reflect.ValueOf(constant.MakeFromLiteral("4028", token.INT, 0)),
			"ErrCodeNoRightToSeeTask": reflect.ValueOf(constant.MakeFromLiteral("4005", token.INT, 0)),
			"ErrCodeOIDCTeamDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("6008", token.INT, 0)),
			"ErrCodeOIDCTeamsDoNotExistForUser": reflect.ValueOf(constant.MakeFromLiteral("6009", token.INT, 0)),
			"ErrCodeOnlyOneDoneBucketPerProject": reflect.ValueOf(constant.MakeFromLiteral("10005", token.INT, 0)),
			"ErrCodeOpenIDError": reflect.ValueOf(constant.MakeFromLiteral("15001", token.INT, 0)),
			"ErrCodeParentTaskCannotBeTheSame": reflect.ValueOf(constant.MakeFromLiteral("4006", token.INT, 0)),
			"ErrCodeProjectCannotBeChildOfItself": reflect.ValueOf(constant.MakeFromLiteral("3010", token.INT, 0)),
			"ErrCodeProjectCannotBelongToAPseudoParentProject": reflect.ValueOf(constant.MakeFromLiteral("3009", token.INT, 0)),
			"ErrCodeProjectCannotHaveACyclicRelationship": reflect.ValueOf(constant.MakeFromLiteral("3011", token.INT, 0)),
			"ErrCodeProjectDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("3001", token.INT, 0)),
			"ErrCodeProjectIdentifierIsNotUnique": reflect.ValueOf(constant.MakeFromLiteral("3007", token.INT, 0)),
			"ErrCodeProjectIsArchived": reflect.ValueOf(constant.MakeFromLiteral("3008", token.INT, 0)),
			"ErrCodeProjectShareDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("3006", token.INT, 0)),
			"ErrCodeProjectTitleCannotBeEmpty": reflect.ValueOf(constant.MakeFromLiteral("3005", token.INT, 0)),
			"ErrCodeProjectViewDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("3014", token.INT, 0)),
			"ErrCodeRelationAlreadyExists": reflect.ValueOf(constant.MakeFromLiteral("4008", token.INT, 0)),
			"ErrCodeRelationDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("4009", token.INT, 0)),
			"ErrCodeRelationTasksCannotBeTheSame": reflect.ValueOf(constant.MakeFromLiteral("4010", token.INT, 0)),
			"ErrCodeReminderRelativeToMissing": reflect.ValueOf(constant.MakeFromLiteral("4022", token.INT, 0)),
			"ErrCodeSavedFilterDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("11001", token.INT, 0)),
			"ErrCodeSavedFilterNotAvailableForLinkShare": reflect.ValueOf(constant.MakeFromLiteral("11002", token.INT, 0)),
			"ErrCodeSubscriptionAlreadyExists": reflect.ValueOf(constant.MakeFromLiteral("12002", token.INT, 0)),
			"ErrCodeTaskAlreadyExistsInBucket": reflect.ValueOf(constant.MakeFromLiteral("10006", token.INT, 0)),
			"ErrCodeTaskAttachmentDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("4011", token.INT, 0)),
			"ErrCodeTaskAttachmentIsTooLarge": reflect.ValueOf(constant.MakeFromLiteral("4012", token.INT, 0)),
			"ErrCodeTaskCannotBeEmpty": reflect.ValueOf(constant.MakeFromLiteral("4001", token.INT, 0)),
			"ErrCodeTaskCommentDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("4015", token.INT, 0)),
			"ErrCodeTaskDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("4002", token.INT, 0)),
			"ErrCodeTaskRelationCycle": reflect.ValueOf(constant.MakeFromLiteral("4023", token.INT, 0)),
			"ErrCodeTeamAlreadyHasAccess": reflect.ValueOf(constant.MakeFromLiteral("6004", token.INT, 0)),
			"ErrCodeTeamDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("6002", token.INT, 0)),
			"ErrCodeTeamDoesNotHaveAccessToProject": reflect.ValueOf(constant.MakeFromLiteral("6007", token.INT, 0)),
			"ErrCodeTeamNameCannotBeEmpty": reflect.ValueOf(constant.MakeFromLiteral("6001", token.INT, 0)),
			"ErrCodeUnknownSubscriptionEntityType": reflect.ValueOf(constant.MakeFromLiteral("12001", token.INT, 0)),
			"ErrCodeUserAlreadyAssigned": reflect.ValueOf(constant.MakeFromLiteral("4021", token.INT, 0)),
			"ErrCodeUserAlreadyHasAccess": reflect.ValueOf(constant.MakeFromLiteral("7002", token.INT, 0)),
			"ErrCodeUserDoesNotHaveAccessToProject": reflect.ValueOf(constant.MakeFromLiteral("7003", token.INT, 0)),
			"ErrCodeUserHasNoAccessToLabel": reflect.ValueOf(constant.MakeFromLiteral("8003", token.INT, 0)),
			"ErrCodeUserIsMemberOfTeam": reflect.ValueOf(constant.MakeFromLiteral("6005", token.INT, 0)),
			"ErrorCodeGenericForbidden": reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
			"ExportUserData": reflect.ValueOf(models.ExportUserData),
			"FavoriteKindProject": reflect.ValueOf(models.FavoriteKindProject),
			"FavoriteKindTask": reflect.ValueOf(models.FavoriteKindTask),
			"FavoriteKindUnknown": reflect.ValueOf(models.FavoriteKindUnknown),
			"FavoritesPseudoProject": reflect.ValueOf(&models.FavoritesPseudoProject).Elem(),
			"FavoritesPseudoProjectID": reflect.ValueOf(constant.MakeFromLiteral("-1", token.INT, 0)),
			"FindMentionedUsersInText": reflect.ValueOf(models.FindMentionedUsersInText),
			"GetAPITokenByID": reflect.ValueOf(models.GetAPITokenByID),
			"GetAllParentProjects": reflect.ValueOf(models.GetAllParentProjects),
			"GetAvailableAPIRoutesForToken": reflect.ValueOf(models.GetAvailableAPIRoutesForToken),
			"GetAvailableWebhookEvents": reflect.ValueOf(models.GetAvailableWebhookEvents),
			"GetLabelSimple": reflect.ValueOf(models.GetLabelSimple),
			"GetLabelsByTaskIDs": reflect.ValueOf(models.GetLabelsByTaskIDs),
			"GetLinkShareByHash": reflect.ValueOf(models.GetLinkShareByHash),
			"GetLinkShareByID": reflect.ValueOf(models.GetLinkShareByID),
			"GetLinkShareFromClaims": reflect.ValueOf(models.GetLinkShareFromClaims),
			"GetLinkSharesByIDs": reflect.ValueOf(models.GetLinkSharesByIDs),
			"GetPreviewSizeFromString": reflect.ValueOf(models.GetPreviewSizeFromString),
			"GetProjectByShareHash": reflect.ValueOf(models.GetProjectByShareHash),
			"GetProjectSimpleByID": reflect.ValueOf(models.GetProjectSimpleByID),
			"GetProjectSimpleByTaskID": reflect.ValueOf(models.GetProjectSimpleByTaskID),
			"GetProjectViewByID": reflect.ValueOf(models.GetProjectViewByID),
			"GetProjectViewByIDAndProject": reflect.ValueOf(models.GetProjectViewByIDAndProject),
			"GetProjectsByIDs": reflect.ValueOf(models.GetProjectsByIDs),
			"GetProjectsMapByIDs": reflect.ValueOf(models.GetProjectsMapByIDs),
			"GetProjectsMapSimpleByTaskIDs": reflect.ValueOf(models.GetProjectsMapSimpleByTaskIDs),
			"GetProjectsSimpleByTaskIDs": reflect.ValueOf(models.GetProjectsSimpleByTaskIDs),
			"GetSavedFilterIDFromProjectID": reflect.ValueOf(models.GetSavedFilterIDFromProjectID),
			"GetSavedFilterSimpleByID": reflect.ValueOf(models.GetSavedFilterSimpleByID),
			"GetSubscriptionForUser": reflect.ValueOf(models.GetSubscriptionForUser),
			"GetSubscriptionsForEntities": reflect.ValueOf(models.GetSubscriptionsForEntities),
			"GetSubscriptionsForEntitiesAndUser": reflect.ValueOf(models.GetSubscriptionsForEntitiesAndUser),
			"GetSubscriptionsForEntity": reflect.ValueOf(models.GetSubscriptionsForEntity),
			"GetTables": reflect.ValueOf(models.GetTables),
			"GetTaskByIDSimple": reflect.ValueOf(models.GetTaskByIDSimple),
			"GetTaskSimple": reflect.ValueOf(models.GetTaskSimple),
			"GetTaskSimpleByUUID": reflect.ValueOf(models.GetTaskSimpleByUUID),
			"GetTasksByUIDs": reflect.ValueOf(models.GetTasksByUIDs),
			"GetTasksInBucketsForView": reflect.ValueOf(models.GetTasksInBucketsForView),
			"GetTasksSimpleByIDs": reflect.ValueOf(models.GetTasksSimpleByIDs),
			"GetTeamByExternalIDAndIssuer": reflect.ValueOf(models.GetTeamByExternalIDAndIssuer),
			"GetTeamByID": reflect.ValueOf(models.GetTeamByID),
			"GetTokenFromTokenString": reflect.ValueOf(models.GetTokenFromTokenString),
			"GetTotalCount": reflect.ValueOf(models.GetTotalCount),
			"GetUnsplashPhotoByFileID": reflect.ValueOf(models.GetUnsplashPhotoByFileID),
			"GetUserOrLinkShareUser": reflect.ValueOf(models.GetUserOrLinkShareUser),
			"HashToken": reflect.ValueOf(models.HashToken),
			"InitTypesense": reflect.ValueOf(models.InitTypesense),
			"InvalidFieldError": reflect.ValueOf(models.InvalidFieldError),
			"InvalidFieldErrorWithMessage": reflect.ValueOf(models.InvalidFieldErrorWithMessage),
			"IsErrAPITokenInvalid": reflect.ValueOf(models.IsErrAPITokenInvalid),
			"IsErrAttachmentAndCoverMustBelongToTheSameTask": reflect.ValueOf(models.IsErrAttachmentAndCoverMustBelongToTheSameTask),
			"IsErrBucketDoesNotBelongToProject": reflect.ValueOf(models.IsErrBucketDoesNotBelongToProject),
			"IsErrBucketDoesNotExist": reflect.ValueOf(models.IsErrBucketDoesNotExist),
			"IsErrBucketLimitExceeded": reflect.ValueOf(models.IsErrBucketLimitExceeded),
			"IsErrBulkTasksMustBeInSameProject": reflect.ValueOf(models.IsErrBulkTasksMustBeInSameProject),
			"IsErrBulkTasksNeedAtLeastOne": reflect.ValueOf(models.IsErrBulkTasksNeedAtLeastOne),
			"IsErrCannotArchiveDefaultProject": reflect.ValueOf(models.IsErrCannotArchiveDefaultProject),
			"IsErrCannotDeleteDefaultProject": reflect.ValueOf(models.IsErrCannotDeleteDefaultProject),
			"IsErrCannotDeleteLastTeamMember": reflect.ValueOf(models.IsErrCannotDeleteLastTeamMember),
			"IsErrCannotRemoveLastBucket": reflect.ValueOf(models.IsErrCannotRemoveLastBucket),
			"IsErrExternalTeamDoesNotExist": reflect.ValueOf(models.IsErrExternalTeamDoesNotExist),
			"IsErrGenericForbidden": reflect.ValueOf(models.IsErrGenericForbidden),
			"IsErrIDCannotBeZero": reflect.ValueOf(models.IsErrIDCannotBeZero),
			"IsErrInvalidAPITokenPermission": reflect.ValueOf(models.IsErrInvalidAPITokenPermission),
			"IsErrInvalidData": reflect.ValueOf(models.IsErrInvalidData),
			"IsErrInvalidFilterExpression": reflect.ValueOf(models.IsErrInvalidFilterExpression),
			"IsErrInvalidModel": reflect.ValueOf(models.IsErrInvalidModel),
			"IsErrInvalidPermission": reflect.ValueOf(models.IsErrInvalidPermission),
			"IsErrInvalidReactionEntityKind": reflect.ValueOf(models.IsErrInvalidReactionEntityKind),
			"IsErrInvalidRelationKind": reflect.ValueOf(models.IsErrInvalidRelationKind),
			"IsErrInvalidSortOrder": reflect.ValueOf(models.IsErrInvalidSortOrder),
			"IsErrInvalidSortParam": reflect.ValueOf(models.IsErrInvalidSortParam),
			"IsErrInvalidTaskColumn": reflect.ValueOf(models.IsErrInvalidTaskColumn),
			"IsErrInvalidTaskField": reflect.ValueOf(models.IsErrInvalidTaskField),
			"IsErrInvalidTaskFilterComparator": reflect.ValueOf(models.IsErrInvalidTaskFilterComparator),
			"IsErrInvalidTaskFilterConcatinator": reflect.ValueOf(models.IsErrInvalidTaskFilterConcatinator),
			"IsErrInvalidTaskFilterValue": reflect.ValueOf(models.IsErrInvalidTaskFilterValue),
			"IsErrInvalidTimezone": reflect.ValueOf(models.IsErrInvalidTimezone),
			"IsErrLabelDoesNotExist": reflect.ValueOf(models.IsErrLabelDoesNotExist),
			"IsErrLabelIsAlreadyOnTask": reflect.ValueOf(models.IsErrLabelIsAlreadyOnTask),
			"IsErrLinkSharePasswordInvalid": reflect.ValueOf(models.IsErrLinkSharePasswordInvalid),
			"IsErrLinkSharePasswordRequired": reflect.ValueOf(models.IsErrLinkSharePasswordRequired),
			"IsErrLinkShareTokenInvalid": reflect.ValueOf(models.IsErrLinkShareTokenInvalid),
			"IsErrMustProvideUser": reflect.ValueOf(models.IsErrMustProvideUser),
			"IsErrNeedToHaveProjectReadAccess": reflect.ValueOf(models.IsErrNeedToHaveProjectReadAccess),
			"IsErrNeedsFullRecalculation": reflect.ValueOf(models.IsErrNeedsFullRecalculation),
			"IsErrNoPermissionToSeeTask": reflect.ValueOf(models.IsErrNoPermissionToSeeTask),
			"IsErrOIDCTeamsDoNotExistForUser": reflect.ValueOf(models.IsErrOIDCTeamsDoNotExistForUser),
			"IsErrOnlyOneDoneBucketPerProject": reflect.ValueOf(models.IsErrOnlyOneDoneBucketPerProject),
			"IsErrParentTaskCannotBeTheSame": reflect.ValueOf(models.IsErrParentTaskCannotBeTheSame),
			"IsErrProjectCannotBeChildOfItsOwn": reflect.ValueOf(models.IsErrProjectCannotBeChildOfItsOwn),
			"IsErrProjectCannotBelongToAPseudoParentProject": reflect.ValueOf(models.IsErrProjectCannotBelongToAPseudoParentProject),
			"IsErrProjectCannotHaveACyclicRelationship": reflect.ValueOf(models.IsErrProjectCannotHaveACyclicRelationship),
			"IsErrProjectDoesNotExist": reflect.ValueOf(models.IsErrProjectDoesNotExist),
			"IsErrProjectIdentifierIsNotUnique": reflect.ValueOf(models.IsErrProjectIdentifierIsNotUnique),
			"IsErrProjectIsArchived": reflect.ValueOf(models.IsErrProjectIsArchived),
			"IsErrProjectShareDoesNotExist": reflect.ValueOf(models.IsErrProjectShareDoesNotExist),
			"IsErrProjectTitleCannotBeEmpty": reflect.ValueOf(models.IsErrProjectTitleCannotBeEmpty),
			"IsErrProjectViewDoesNotExist": reflect.ValueOf(models.IsErrProjectViewDoesNotExist),
			"IsErrRelationAlreadyExists": reflect.ValueOf(models.IsErrRelationAlreadyExists),
			"IsErrRelationDoesNotExist": reflect.ValueOf(models.IsErrRelationDoesNotExist),
			"IsErrRelationTasksCannotBeTheSame": reflect.ValueOf(models.IsErrRelationTasksCannotBeTheSame),
			"IsErrReminderRelativeToMissing": reflect.ValueOf(models.IsErrReminderRelativeToMissing),
			"IsErrSavedFilterDoesNotExist": reflect.ValueOf(models.IsErrSavedFilterDoesNotExist),
			"IsErrSavedFilterNotAvailableForLinkShare": reflect.ValueOf(models.IsErrSavedFilterNotAvailableForLinkShare),
			"IsErrSubscriptionAlreadyExists": reflect.ValueOf(models.IsErrSubscriptionAlreadyExists),
			"IsErrTaskAlreadyExistsInBucket": reflect.ValueOf(models.IsErrTaskAlreadyExistsInBucket),
			"IsErrTaskAttachmentDoesNotExist": reflect.ValueOf(models.IsErrTaskAttachmentDoesNotExist),
			"IsErrTaskAttachmentIsTooLarge": reflect.ValueOf(models.IsErrTaskAttachmentIsTooLarge),
			"IsErrTaskCannotBeEmpty": reflect.ValueOf(models.IsErrTaskCannotBeEmpty),
			"IsErrTaskCommentDoesNotExist": reflect.ValueOf(models.IsErrTaskCommentDoesNotExist),
			"IsErrTaskDoesNotExist": reflect.ValueOf(models.IsErrTaskDoesNotExist),
			"IsErrTaskRelationCycle": reflect.ValueOf(models.IsErrTaskRelationCycle),
			"IsErrTeamAlreadyHasAccess": reflect.ValueOf(models.IsErrTeamAlreadyHasAccess),
			"IsErrTeamDoesNotExist": reflect.ValueOf(models.IsErrTeamDoesNotExist),
			"IsErrTeamDoesNotHaveAccessToProject": reflect.ValueOf(models.IsErrTeamDoesNotHaveAccessToProject),
			"IsErrTeamNameCannotBeEmpty": reflect.ValueOf(models.IsErrTeamNameCannotBeEmpty),
			"IsErrUnknownSubscriptionEntityType": reflect.ValueOf(models.IsErrUnknownSubscriptionEntityType),
			"IsErrUserAlreadyAssigned": reflect.ValueOf(models.IsErrUserAlreadyAssigned),
			"IsErrUserAlreadyHasAccess": reflect.ValueOf(models.IsErrUserAlreadyHasAccess),
			"IsErrUserDoesNotHaveAccessToProject": reflect.ValueOf(models.IsErrUserDoesNotHaveAccessToProject),
			"IsErrUserHasNoAccessToLabel": reflect.ValueOf(models.IsErrUserHasNoAccessToLabel),
			"IsErrUserIsMemberOfTeam": reflect.ValueOf(models.IsErrUserIsMemberOfTeam),
			"ListUsersFromProject": reflect.ValueOf(models.ListUsersFromProject),
			"MinPositionSpacing": reflect.ValueOf(constant.MakeFromLiteral("0.009999999999999999999796712092658967918623602599836885929107666016", token.FLOAT, 0)),
			"PermissionAdmin": reflect.ValueOf(models.PermissionAdmin),
			"PermissionRead": reflect.ValueOf(models.PermissionRead),
			"PermissionUnknown": reflect.ValueOf(constant.MakeFromLiteral("-1", token.INT, 0)),
			"PermissionWrite": reflect.ValueOf(models.PermissionWrite),
			"PermissionsAreValid": reflect.ValueOf(models.PermissionsAreValid),
			"PreviewExtraLarge": reflect.ValueOf(models.PreviewExtraLarge),
			"PreviewLarge": reflect.ValueOf(models.PreviewLarge),
			"PreviewMedium": reflect.ValueOf(models.PreviewMedium),
			"PreviewSizeUnknown": reflect.ValueOf(models.PreviewSizeUnknown),
			"PreviewSmall": reflect.ValueOf(models.PreviewSmall),
			"ProjectBackgroundUpload": reflect.ValueOf(models.ProjectBackgroundUpload),
			"ProjectExpandableRights": reflect.ValueOf(constant.MakeFromLiteral("\"permissions\"", token.STRING, 0)),
			"ProjectViewKindGantt": reflect.ValueOf(models.ProjectViewKindGantt),
			"ProjectViewKindKanban": reflect.ValueOf(models.ProjectViewKindKanban),
			"ProjectViewKindList": reflect.ValueOf(models.ProjectViewKindList),
			"ProjectViewKindTable": reflect.ValueOf(models.ProjectViewKindTable),
			"ReactionKindComment": reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
			"ReactionKindTask": reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
			"RecalculateTaskPositions": reflect.ValueOf(models.RecalculateTaskPositions),
			"RegisterAddTaskToFilterViewCron": reflect.ValueOf(models.RegisterAddTaskToFilterViewCron),
			"RegisterEventForWebhook": reflect.ValueOf(models.RegisterEventForWebhook),
			"RegisterListeners": reflect.ValueOf(models.RegisterListeners),
			"RegisterOldExportCleanupCron": reflect.ValueOf(models.RegisterOldExportCleanupCron),
			"RegisterOverdueReminderCron": reflect.ValueOf(models.RegisterOverdueReminderCron),
			"RegisterReminderCron": reflect.ValueOf(models.RegisterReminderCron),
			"RegisterUserDeletionCron": reflect.ValueOf(models.RegisterUserDeletionCron),
			"ReindexAllTasks": reflect.ValueOf(models.ReindexAllTasks),
			"RelationKindBlocked": reflect.ValueOf(models.RelationKindBlocked),
			"RelationKindBlocking": reflect.ValueOf(models.RelationKindBlocking),
			"RelationKindCopiedFrom": reflect.ValueOf(models.RelationKindCopiedFrom),
			"RelationKindCopiedTo": reflect.ValueOf(models.RelationKindCopiedTo),
			"RelationKindDuplicateOf": reflect.ValueOf(models.RelationKindDuplicateOf),
			"RelationKindDuplicates": reflect.ValueOf(models.RelationKindDuplicates),
			"RelationKindFollows": reflect.ValueOf(models.RelationKindFollows),
			"RelationKindParenttask": reflect.ValueOf(models.RelationKindParenttask),
			"RelationKindPreceeds": reflect.ValueOf(models.RelationKindPreceeds),
			"RelationKindRelated": reflect.ValueOf(models.RelationKindRelated),
			"RelationKindSubtask": reflect.ValueOf(models.RelationKindSubtask),
			"RelationKindUnknown": reflect.ValueOf(models.RelationKindUnknown),
			"ReminderRelationDueDate": reflect.ValueOf(models.ReminderRelationDueDate),
			"ReminderRelationEndDate": reflect.ValueOf(models.ReminderRelationEndDate),
			"ReminderRelationStartDate": reflect.ValueOf(models.ReminderRelationStartDate),
			"RemoveUnsplashPhoto": reflect.ValueOf(models.RemoveUnsplashPhoto),
			"RepairTaskPositions": reflect.ValueOf(models.RepairTaskPositions),
			"SetEngine": reflect.ValueOf(models.SetEngine),
			"SetProjectBackground": reflect.ValueOf(models.SetProjectBackground),
			"SetupTests": reflect.ValueOf(models.SetupTests),
			"SharingTypeUnknown": reflect.ValueOf(models.SharingTypeUnknown),
			"SharingTypeWithPassword": reflect.ValueOf(models.SharingTypeWithPassword),
			"SharingTypeWithoutPassword": reflect.ValueOf(models.SharingTypeWithoutPassword),
			"SubscriptionEntityNamespace": reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
			"SubscriptionEntityProject": reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
			"SubscriptionEntityTask": reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
			"SubscriptionEntityUnknown": reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
			"SyncExternalTeamsForUser": reflect.ValueOf(models.SyncExternalTeamsForUser),
			"SyncUpdatedTasksIntoTypesense": reflect.ValueOf(models.SyncUpdatedTasksIntoTypesense),
			"TaskCollectionExpandBuckets": reflect.ValueOf(models.TaskCollectionExpandBuckets),
			"TaskCollectionExpandCommentCount": reflect.ValueOf(models.TaskCollectionExpandCommentCount),
			"TaskCollectionExpandComments": reflect.ValueOf(models.TaskCollectionExpandComments),
			"TaskCollectionExpandIsUnread": reflect.ValueOf(models.TaskCollectionExpandIsUnread),
			"TaskCollectionExpandReactions": reflect.ValueOf(models.TaskCollectionExpandReactions),
			"TaskCollectionExpandSubtasks": reflect.ValueOf(models.TaskCollectionExpandSubtasks),
			"TaskRepeatModeDefault": reflect.ValueOf(models.TaskRepeatModeDefault),
			"TaskRepeatModeFromCurrentDate": reflect.ValueOf(models.TaskRepeatModeFromCurrentDate),
			"TaskRepeatModeMonth": reflect.ValueOf(models.TaskRepeatModeMonth),
			"UpdateProject": reflect.ValueOf(models.UpdateProject),
			"VerifyLinkSharePassword": reflect.ValueOf(models.VerifyLinkSharePassword),
			
		// type definitions
		"APIPermissions": reflect.ValueOf((*models.APIPermissions)(nil)),
		"APIToken": reflect.ValueOf((*models.APIToken)(nil)),
		"APITokenRoute": reflect.ValueOf((*models.APITokenRoute)(nil)),
		"AddTaskToTypesense": reflect.ValueOf((*models.AddTaskToTypesense)(nil)),
		"Bucket": reflect.ValueOf((*models.Bucket)(nil)),
		"BucketConfigurationModeKind": reflect.ValueOf((*models.BucketConfigurationModeKind)(nil)),
		"BulkAssignees": reflect.ValueOf((*models.BulkAssignees)(nil)),
		"BulkTask": reflect.ValueOf((*models.BulkTask)(nil)),
		"CleanupTaskAssignmentsAfterTeamRemoval": reflect.ValueOf((*models.CleanupTaskAssignmentsAfterTeamRemoval)(nil)),
		"DataExportReadyNotification": reflect.ValueOf((*models.DataExportReadyNotification)(nil)),
		"DatabaseNotifications": reflect.ValueOf((*models.DatabaseNotifications)(nil)),
		"DecreaseAttachmentCounter": reflect.ValueOf((*models.DecreaseAttachmentCounter)(nil)),
		"DecreaseProjectCounter": reflect.ValueOf((*models.DecreaseProjectCounter)(nil)),
		"DecreaseTaskCounter": reflect.ValueOf((*models.DecreaseTaskCounter)(nil)),
		"DecreaseTeamCounter": reflect.ValueOf((*models.DecreaseTeamCounter)(nil)),
		"ErrAPITokenInvalid": reflect.ValueOf((*models.ErrAPITokenInvalid)(nil)),
		"ErrAttachmentDoesNotBelongToTask": reflect.ValueOf((*models.ErrAttachmentDoesNotBelongToTask)(nil)),
		"ErrBucketDoesNotBelongToProjectView": reflect.ValueOf((*models.ErrBucketDoesNotBelongToProjectView)(nil)),
		"ErrBucketDoesNotExist": reflect.ValueOf((*models.ErrBucketDoesNotExist)(nil)),
		"ErrBucketLimitExceeded": reflect.ValueOf((*models.ErrBucketLimitExceeded)(nil)),
		"ErrBulkTasksMustBeInSameProject": reflect.ValueOf((*models.ErrBulkTasksMustBeInSameProject)(nil)),
		"ErrBulkTasksNeedAtLeastOne": reflect.ValueOf((*models.ErrBulkTasksNeedAtLeastOne)(nil)),
		"ErrCannotArchiveDefaultProject": reflect.ValueOf((*models.ErrCannotArchiveDefaultProject)(nil)),
		"ErrCannotDeleteDefaultProject": reflect.ValueOf((*models.ErrCannotDeleteDefaultProject)(nil)),
		"ErrCannotDeleteLastTeamMember": reflect.ValueOf((*models.ErrCannotDeleteLastTeamMember)(nil)),
		"ErrCannotRemoveLastBucket": reflect.ValueOf((*models.ErrCannotRemoveLastBucket)(nil)),
		"ErrCannotRemoveUserFromExternalTeam": reflect.ValueOf((*models.ErrCannotRemoveUserFromExternalTeam)(nil)),
		"ErrExternalTeamDoesNotExist": reflect.ValueOf((*models.ErrExternalTeamDoesNotExist)(nil)),
		"ErrGenericForbidden": reflect.ValueOf((*models.ErrGenericForbidden)(nil)),
		"ErrIDCannotBeZero": reflect.ValueOf((*models.ErrIDCannotBeZero)(nil)),
		"ErrInvalidAPITokenPermission": reflect.ValueOf((*models.ErrInvalidAPITokenPermission)(nil)),
		"ErrInvalidData": reflect.ValueOf((*models.ErrInvalidData)(nil)),
		"ErrInvalidFilterExpression": reflect.ValueOf((*models.ErrInvalidFilterExpression)(nil)),
		"ErrInvalidModel": reflect.ValueOf((*models.ErrInvalidModel)(nil)),
		"ErrInvalidPermission": reflect.ValueOf((*models.ErrInvalidPermission)(nil)),
		"ErrInvalidReactionEntityKind": reflect.ValueOf((*models.ErrInvalidReactionEntityKind)(nil)),
		"ErrInvalidRelationKind": reflect.ValueOf((*models.ErrInvalidRelationKind)(nil)),
		"ErrInvalidSortOrder": reflect.ValueOf((*models.ErrInvalidSortOrder)(nil)),
		"ErrInvalidSortParam": reflect.ValueOf((*models.ErrInvalidSortParam)(nil)),
		"ErrInvalidTaskColumn": reflect.ValueOf((*models.ErrInvalidTaskColumn)(nil)),
		"ErrInvalidTaskField": reflect.ValueOf((*models.ErrInvalidTaskField)(nil)),
		"ErrInvalidTaskFilterComparator": reflect.ValueOf((*models.ErrInvalidTaskFilterComparator)(nil)),
		"ErrInvalidTaskFilterConcatinator": reflect.ValueOf((*models.ErrInvalidTaskFilterConcatinator)(nil)),
		"ErrInvalidTaskFilterValue": reflect.ValueOf((*models.ErrInvalidTaskFilterValue)(nil)),
		"ErrInvalidTimezone": reflect.ValueOf((*models.ErrInvalidTimezone)(nil)),
		"ErrLabelDoesNotExist": reflect.ValueOf((*models.ErrLabelDoesNotExist)(nil)),
		"ErrLabelIsAlreadyOnTask": reflect.ValueOf((*models.ErrLabelIsAlreadyOnTask)(nil)),
		"ErrLinkSharePasswordInvalid": reflect.ValueOf((*models.ErrLinkSharePasswordInvalid)(nil)),
		"ErrLinkSharePasswordRequired": reflect.ValueOf((*models.ErrLinkSharePasswordRequired)(nil)),
		"ErrLinkShareTokenInvalid": reflect.ValueOf((*models.ErrLinkShareTokenInvalid)(nil)),
		"ErrMustHaveProjectViewToSortByPosition": reflect.ValueOf((*models.ErrMustHaveProjectViewToSortByPosition)(nil)),
		"ErrMustProvideUser": reflect.ValueOf((*models.ErrMustProvideUser)(nil)),
		"ErrNeedToHaveProjectReadAccess": reflect.ValueOf((*models.ErrNeedToHaveProjectReadAccess)(nil)),
		"ErrNeedsFullRecalculation": reflect.ValueOf((*models.ErrNeedsFullRecalculation)(nil)),
		"ErrNoPermissionToSeeTask": reflect.ValueOf((*models.ErrNoPermissionToSeeTask)(nil)),
		"ErrOIDCTeamsDoNotExistForUser": reflect.ValueOf((*models.ErrOIDCTeamsDoNotExistForUser)(nil)),
		"ErrOnlyOneDoneBucketPerProject": reflect.ValueOf((*models.ErrOnlyOneDoneBucketPerProject)(nil)),
		"ErrOpenIDBadRequest": reflect.ValueOf((*models.ErrOpenIDBadRequest)(nil)),
		"ErrOpenIDBadRequestWithDetails": reflect.ValueOf((*models.ErrOpenIDBadRequestWithDetails)(nil)),
		"ErrParentTaskCannotBeTheSame": reflect.ValueOf((*models.ErrParentTaskCannotBeTheSame)(nil)),
		"ErrProjectCannotBeChildOfItself": reflect.ValueOf((*models.ErrProjectCannotBeChildOfItself)(nil)),
		"ErrProjectCannotBelongToAPseudoParentProject": reflect.ValueOf((*models.ErrProjectCannotBelongToAPseudoParentProject)(nil)),
		"ErrProjectCannotHaveACyclicRelationship": reflect.ValueOf((*models.ErrProjectCannotHaveACyclicRelationship)(nil)),
		"ErrProjectDoesNotExist": reflect.ValueOf((*models.ErrProjectDoesNotExist)(nil)),
		"ErrProjectIdentifierIsNotUnique": reflect.ValueOf((*models.ErrProjectIdentifierIsNotUnique)(nil)),
		"ErrProjectIsArchived": reflect.ValueOf((*models.ErrProjectIsArchived)(nil)),
		"ErrProjectShareDoesNotExist": reflect.ValueOf((*models.ErrProjectShareDoesNotExist)(nil)),
		"ErrProjectTitleCannotBeEmpty": reflect.ValueOf((*models.ErrProjectTitleCannotBeEmpty)(nil)),
		"ErrProjectViewDoesNotExist": reflect.ValueOf((*models.ErrProjectViewDoesNotExist)(nil)),
		"ErrRelationAlreadyExists": reflect.ValueOf((*models.ErrRelationAlreadyExists)(nil)),
		"ErrRelationDoesNotExist": reflect.ValueOf((*models.ErrRelationDoesNotExist)(nil)),
		"ErrRelationTasksCannotBeTheSame": reflect.ValueOf((*models.ErrRelationTasksCannotBeTheSame)(nil)),
		"ErrReminderRelativeToMissing": reflect.ValueOf((*models.ErrReminderRelativeToMissing)(nil)),
		"ErrSavedFilterDoesNotExist": reflect.ValueOf((*models.ErrSavedFilterDoesNotExist)(nil)),
		"ErrSavedFilterNotAvailableForLinkShare": reflect.ValueOf((*models.ErrSavedFilterNotAvailableForLinkShare)(nil)),
		"ErrSubscriptionAlreadyExists": reflect.ValueOf((*models.ErrSubscriptionAlreadyExists)(nil)),
		"ErrTaskAlreadyExistsInBucket": reflect.ValueOf((*models.ErrTaskAlreadyExistsInBucket)(nil)),
		"ErrTaskAttachmentDoesNotExist": reflect.ValueOf((*models.ErrTaskAttachmentDoesNotExist)(nil)),
		"ErrTaskAttachmentIsTooLarge": reflect.ValueOf((*models.ErrTaskAttachmentIsTooLarge)(nil)),
		"ErrTaskCannotBeEmpty": reflect.ValueOf((*models.ErrTaskCannotBeEmpty)(nil)),
		"ErrTaskCommentDoesNotExist": reflect.ValueOf((*models.ErrTaskCommentDoesNotExist)(nil)),
		"ErrTaskDoesNotExist": reflect.ValueOf((*models.ErrTaskDoesNotExist)(nil)),
		"ErrTaskRelationCycle": reflect.ValueOf((*models.ErrTaskRelationCycle)(nil)),
		"ErrTeamAlreadyHasAccess": reflect.ValueOf((*models.ErrTeamAlreadyHasAccess)(nil)),
		"ErrTeamDoesNotExist": reflect.ValueOf((*models.ErrTeamDoesNotExist)(nil)),
		"ErrTeamDoesNotHaveAccessToProject": reflect.ValueOf((*models.ErrTeamDoesNotHaveAccessToProject)(nil)),
		"ErrTeamNameCannotBeEmpty": reflect.ValueOf((*models.ErrTeamNameCannotBeEmpty)(nil)),
		"ErrUnknownSubscriptionEntityType": reflect.ValueOf((*models.ErrUnknownSubscriptionEntityType)(nil)),
		"ErrUserAlreadyAssigned": reflect.ValueOf((*models.ErrUserAlreadyAssigned)(nil)),
		"ErrUserAlreadyHasAccess": reflect.ValueOf((*models.ErrUserAlreadyHasAccess)(nil)),
		"ErrUserDoesNotHaveAccessToProject": reflect.ValueOf((*models.ErrUserDoesNotHaveAccessToProject)(nil)),
		"ErrUserHasNoAccessToLabel": reflect.ValueOf((*models.ErrUserHasNoAccessToLabel)(nil)),
		"ErrUserIsMemberOfTeam": reflect.ValueOf((*models.ErrUserIsMemberOfTeam)(nil)),
		"Favorite": reflect.ValueOf((*models.Favorite)(nil)),
		"FavoriteKind": reflect.ValueOf((*models.FavoriteKind)(nil)),
		"HandleTaskCommentEditMentions": reflect.ValueOf((*models.HandleTaskCommentEditMentions)(nil)),
		"HandleTaskCreateMentions": reflect.ValueOf((*models.HandleTaskCreateMentions)(nil)),
		"HandleTaskUpdateLastUpdated": reflect.ValueOf((*models.HandleTaskUpdateLastUpdated)(nil)),
		"HandleTaskUpdatedMentions": reflect.ValueOf((*models.HandleTaskUpdatedMentions)(nil)),
		"HandleUserDataExport": reflect.ValueOf((*models.HandleUserDataExport)(nil)),
		"IncreaseAttachmentCounter": reflect.ValueOf((*models.IncreaseAttachmentCounter)(nil)),
		"IncreaseProjectCounter": reflect.ValueOf((*models.IncreaseProjectCounter)(nil)),
		"IncreaseTaskCounter": reflect.ValueOf((*models.IncreaseTaskCounter)(nil)),
		"IncreaseTeamCounter": reflect.ValueOf((*models.IncreaseTeamCounter)(nil)),
		"Label": reflect.ValueOf((*models.Label)(nil)),
		"LabelByTaskIDsOptions": reflect.ValueOf((*models.LabelByTaskIDsOptions)(nil)),
		"LabelTask": reflect.ValueOf((*models.LabelTask)(nil)),
		"LabelTaskBulk": reflect.ValueOf((*models.LabelTaskBulk)(nil)),
		"LabelWithTaskID": reflect.ValueOf((*models.LabelWithTaskID)(nil)),
		"LinkSharing": reflect.ValueOf((*models.LinkSharing)(nil)),
		"MarkTaskUnreadOnComment": reflect.ValueOf((*models.MarkTaskUnreadOnComment)(nil)),
		"Message": reflect.ValueOf((*models.Message)(nil)),
		"Permission": reflect.ValueOf((*models.Permission)(nil)),
		"PreviewSize": reflect.ValueOf((*models.PreviewSize)(nil)),
		"Project": reflect.ValueOf((*models.Project)(nil)),
		"ProjectBackgroundType": reflect.ValueOf((*models.ProjectBackgroundType)(nil)),
		"ProjectCreatedEvent": reflect.ValueOf((*models.ProjectCreatedEvent)(nil)),
		"ProjectCreatedNotification": reflect.ValueOf((*models.ProjectCreatedNotification)(nil)),
		"ProjectDeletedEvent": reflect.ValueOf((*models.ProjectDeletedEvent)(nil)),
		"ProjectDuplicate": reflect.ValueOf((*models.ProjectDuplicate)(nil)),
		"ProjectExpandable": reflect.ValueOf((*models.ProjectExpandable)(nil)),
		"ProjectSharedWithTeamEvent": reflect.ValueOf((*models.ProjectSharedWithTeamEvent)(nil)),
		"ProjectSharedWithUserEvent": reflect.ValueOf((*models.ProjectSharedWithUserEvent)(nil)),
		"ProjectUIDs": reflect.ValueOf((*models.ProjectUIDs)(nil)),
		"ProjectUpdatedEvent": reflect.ValueOf((*models.ProjectUpdatedEvent)(nil)),
		"ProjectUser": reflect.ValueOf((*models.ProjectUser)(nil)),
		"ProjectView": reflect.ValueOf((*models.ProjectView)(nil)),
		"ProjectViewBucketConfiguration": reflect.ValueOf((*models.ProjectViewBucketConfiguration)(nil)),
		"ProjectViewKind": reflect.ValueOf((*models.ProjectViewKind)(nil)),
		"ProjectWithTasksAndBuckets": reflect.ValueOf((*models.ProjectWithTasksAndBuckets)(nil)),
		"Reaction": reflect.ValueOf((*models.Reaction)(nil)),
		"ReactionKind": reflect.ValueOf((*models.ReactionKind)(nil)),
		"ReactionMap": reflect.ValueOf((*models.ReactionMap)(nil)),
		"RelatedTaskMap": reflect.ValueOf((*models.RelatedTaskMap)(nil)),
		"RelationKind": reflect.ValueOf((*models.RelationKind)(nil)),
		"ReminderDueNotification": reflect.ValueOf((*models.ReminderDueNotification)(nil)),
		"ReminderRelation": reflect.ValueOf((*models.ReminderRelation)(nil)),
		"RemoveTaskFromTypesense": reflect.ValueOf((*models.RemoveTaskFromTypesense)(nil)),
		"RepairResult": reflect.ValueOf((*models.RepairResult)(nil)),
		"RouteDetail": reflect.ValueOf((*models.RouteDetail)(nil)),
		"SavedFilter": reflect.ValueOf((*models.SavedFilter)(nil)),
		"SendProjectCreatedNotification": reflect.ValueOf((*models.SendProjectCreatedNotification)(nil)),
		"SendTaskAssignedNotification": reflect.ValueOf((*models.SendTaskAssignedNotification)(nil)),
		"SendTaskCommentNotification": reflect.ValueOf((*models.SendTaskCommentNotification)(nil)),
		"SendTaskDeletedNotification": reflect.ValueOf((*models.SendTaskDeletedNotification)(nil)),
		"SendTeamMemberAddedNotification": reflect.ValueOf((*models.SendTeamMemberAddedNotification)(nil)),
		"SharingType": reflect.ValueOf((*models.SharingType)(nil)),
		"SubTableFilter": reflect.ValueOf((*models.SubTableFilter)(nil)),
		"SubTableFilters": reflect.ValueOf((*models.SubTableFilters)(nil)),
		"Subscription": reflect.ValueOf((*models.Subscription)(nil)),
		"SubscriptionEntityType": reflect.ValueOf((*models.SubscriptionEntityType)(nil)),
		"SubscriptionWithUser": reflect.ValueOf((*models.SubscriptionWithUser)(nil)),
		"Task": reflect.ValueOf((*models.Task)(nil)),
		"TaskAssginee": reflect.ValueOf((*models.TaskAssginee)(nil)),
		"TaskAssignedNotification": reflect.ValueOf((*models.TaskAssignedNotification)(nil)),
		"TaskAssigneeCreatedEvent": reflect.ValueOf((*models.TaskAssigneeCreatedEvent)(nil)),
		"TaskAssigneeDeletedEvent": reflect.ValueOf((*models.TaskAssigneeDeletedEvent)(nil)),
		"TaskAssigneeWithUser": reflect.ValueOf((*models.TaskAssigneeWithUser)(nil)),
		"TaskAttachment": reflect.ValueOf((*models.TaskAttachment)(nil)),
		"TaskAttachmentCreatedEvent": reflect.ValueOf((*models.TaskAttachmentCreatedEvent)(nil)),
		"TaskAttachmentDeletedEvent": reflect.ValueOf((*models.TaskAttachmentDeletedEvent)(nil)),
		"TaskBucket": reflect.ValueOf((*models.TaskBucket)(nil)),
		"TaskCollection": reflect.ValueOf((*models.TaskCollection)(nil)),
		"TaskCollectionExpandable": reflect.ValueOf((*models.TaskCollectionExpandable)(nil)),
		"TaskComment": reflect.ValueOf((*models.TaskComment)(nil)),
		"TaskCommentCreatedEvent": reflect.ValueOf((*models.TaskCommentCreatedEvent)(nil)),
		"TaskCommentDeletedEvent": reflect.ValueOf((*models.TaskCommentDeletedEvent)(nil)),
		"TaskCommentNotification": reflect.ValueOf((*models.TaskCommentNotification)(nil)),
		"TaskCommentUpdatedEvent": reflect.ValueOf((*models.TaskCommentUpdatedEvent)(nil)),
		"TaskCreatedEvent": reflect.ValueOf((*models.TaskCreatedEvent)(nil)),
		"TaskDeletedEvent": reflect.ValueOf((*models.TaskDeletedEvent)(nil)),
		"TaskDeletedNotification": reflect.ValueOf((*models.TaskDeletedNotification)(nil)),
		"TaskPosition": reflect.ValueOf((*models.TaskPosition)(nil)),
		"TaskPositionWithView": reflect.ValueOf((*models.TaskPositionWithView)(nil)),
		"TaskPositionsRecalculatedEvent": reflect.ValueOf((*models.TaskPositionsRecalculatedEvent)(nil)),
		"TaskRelation": reflect.ValueOf((*models.TaskRelation)(nil)),
		"TaskRelationCreatedEvent": reflect.ValueOf((*models.TaskRelationCreatedEvent)(nil)),
		"TaskRelationDeletedEvent": reflect.ValueOf((*models.TaskRelationDeletedEvent)(nil)),
		"TaskReminder": reflect.ValueOf((*models.TaskReminder)(nil)),
		"TaskRepeatMode": reflect.ValueOf((*models.TaskRepeatMode)(nil)),
		"TaskUnreadStatus": reflect.ValueOf((*models.TaskUnreadStatus)(nil)),
		"TaskUpdatedEvent": reflect.ValueOf((*models.TaskUpdatedEvent)(nil)),
		"TaskWithComments": reflect.ValueOf((*models.TaskWithComments)(nil)),
		"Team": reflect.ValueOf((*models.Team)(nil)),
		"TeamCreatedEvent": reflect.ValueOf((*models.TeamCreatedEvent)(nil)),
		"TeamDeletedEvent": reflect.ValueOf((*models.TeamDeletedEvent)(nil)),
		"TeamMember": reflect.ValueOf((*models.TeamMember)(nil)),
		"TeamMemberAddedEvent": reflect.ValueOf((*models.TeamMemberAddedEvent)(nil)),
		"TeamMemberAddedNotification": reflect.ValueOf((*models.TeamMemberAddedNotification)(nil)),
		"TeamMemberRemovedEvent": reflect.ValueOf((*models.TeamMemberRemovedEvent)(nil)),
		"TeamProject": reflect.ValueOf((*models.TeamProject)(nil)),
		"TeamUser": reflect.ValueOf((*models.TeamUser)(nil)),
		"TeamWithPermission": reflect.ValueOf((*models.TeamWithPermission)(nil)),
		"TypesenseSync": reflect.ValueOf((*models.TypesenseSync)(nil)),
		"UndoneTaskOverdueNotification": reflect.ValueOf((*models.UndoneTaskOverdueNotification)(nil)),
		"UndoneTasksOverdueNotification": reflect.ValueOf((*models.UndoneTasksOverdueNotification)(nil)),
		"UnsplashPhoto": reflect.ValueOf((*models.UnsplashPhoto)(nil)),
		"UpdateTaskInSavedFilterViews": reflect.ValueOf((*models.UpdateTaskInSavedFilterViews)(nil)),
		"UpdateTaskInTypesense": reflect.ValueOf((*models.UpdateTaskInTypesense)(nil)),
		"UpdateTaskPositionsInTypesense": reflect.ValueOf((*models.UpdateTaskPositionsInTypesense)(nil)),
		"UserDataExportRequestedEvent": reflect.ValueOf((*models.UserDataExportRequestedEvent)(nil)),
		"UserMentionedInTaskNotification": reflect.ValueOf((*models.UserMentionedInTaskNotification)(nil)),
		"UserWithPermission": reflect.ValueOf((*models.UserWithPermission)(nil)),
		"ValidationHTTPError": reflect.ValueOf((*models.ValidationHTTPError)(nil)),
		"Webhook": reflect.ValueOf((*models.Webhook)(nil)),
		"WebhookListener": reflect.ValueOf((*models.WebhookListener)(nil)),
		"WebhookPayload": reflect.ValueOf((*models.WebhookPayload)(nil)),
		
	}
}
