// Vikunja is a to-do list application to facilitate your life.
// Copyright 2018-present Vikunja and contributors. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

package apiv2

import (
	"context"
	"errors"
	"net/http"
	"time"

	"code.vikunja.io/api/pkg/config"
	"code.vikunja.io/api/pkg/db"
	"code.vikunja.io/api/pkg/i18n"
	"code.vikunja.io/api/pkg/modules/auth"
	"code.vikunja.io/api/pkg/notifications"
	"code.vikunja.io/api/pkg/user"

	"github.com/danielgtaylor/huma/v2"
)

type webPushKeysInput struct {
	P256DH string `json:"p256dh" required:"true" doc:"The browser subscription P-256 public key."`
	Auth   string `json:"auth" required:"true" doc:"The browser subscription authentication secret."`
}

type webPushSubscriptionInput struct {
	Endpoint       string           `json:"endpoint" required:"true" doc:"The HTTPS endpoint returned by PushManager.subscribe."`
	ExpirationTime *int64           `json:"expiration_time,omitempty" doc:"Optional subscription expiration as Unix milliseconds."`
	Keys           webPushKeysInput `json:"keys" required:"true"`
}

type webPushSubscriptionOutput struct {
	ID       int64     `json:"id" readOnly:"true"`
	DeviceID string    `json:"device_id" readOnly:"true"`
	Created  time.Time `json:"created" readOnly:"true"`
	Updated  time.Time `json:"updated" readOnly:"true"`
}

type webPushSubscriptionBody struct {
	Body webPushSubscriptionOutput
}

type webPushTestBody struct {
	Body struct {
		Accepted bool `json:"accepted" readOnly:"true"`
	}
}

func RegisterWebPushRoutes(api huma.API) {
	if !config.WebPushEnabled.GetBool() {
		return
	}
	tags := []string{"notifications"}
	Register(api, huma.Operation{
		OperationID: "web-push-subscription-upsert",
		Summary:     "Enable Web Push on this device",
		Description: "Creates or refreshes the authenticated session's browser subscription. Endpoint and encryption keys are write-only.",
		Method:      http.MethodPut,
		Path:        "/user/settings/web-push/subscriptions/{device_id}",
		Tags:        tags,
	}, webPushSubscriptionUpsert)
	Register(api, huma.Operation{
		OperationID:   "web-push-subscription-delete",
		Summary:       "Disable Web Push on this device",
		Description:   "Removes the current user's device subscription and all pending deliveries.",
		Method:        http.MethodDelete,
		Path:          "/user/settings/web-push/subscriptions/{device_id}",
		DefaultStatus: http.StatusNoContent,
		Tags:          tags,
	}, webPushSubscriptionDelete)
	Register(api, huma.Operation{
		OperationID:   "web-push-subscription-test",
		Summary:       "Test Web Push on this device",
		Description:   "Sends a test notification directly and reports whether the browser push service accepted it.",
		Method:        http.MethodPost,
		Path:          "/user/settings/web-push/subscriptions/{device_id}/test",
		DefaultStatus: http.StatusOK,
		Tags:          tags,
	}, webPushSubscriptionTest)
}

func init() { AddRouteRegistrar(RegisterWebPushRoutes) }

func webPushSession(ctx context.Context) (userID int64, sessionID string, err error) {
	a, err := authFromCtx(ctx)
	if err != nil {
		return 0, "", err
	}
	ec := echoContextFromCtx(ctx)
	if ec == nil {
		return 0, "", huma.Error401Unauthorized("invalid or missing authentication")
	}
	sessionID = auth.SessionIDFromContext(ec)
	if sessionID == "" {
		return 0, "", huma.Error403Forbidden("web push requires a user session")
	}
	return a.GetID(), sessionID, nil
}

func webPushSubscriptionUpsert(ctx context.Context, in *struct {
	DeviceID string `path:"device_id" doc:"A stable UUID generated by this browser installation."`
	Body     webPushSubscriptionInput
}) (*webPushSubscriptionBody, error) {
	userID, sessionID, err := webPushSession(ctx)
	if err != nil {
		return nil, err
	}
	var expiration *time.Time
	if in.Body.ExpirationTime != nil {
		parsed := time.UnixMilli(*in.Body.ExpirationTime)
		expiration = &parsed
	}
	s := db.NewSession()
	defer s.Close()
	subscription, err := notifications.UpsertWebPushSubscription(s, userID, sessionID, in.DeviceID, notifications.WebPushSubscriptionInput{
		Endpoint:       in.Body.Endpoint,
		P256DH:         in.Body.Keys.P256DH,
		Auth:           in.Body.Keys.Auth,
		ExpirationTime: expiration,
	})
	if err != nil {
		_ = s.Rollback()
		var owned notifications.ErrWebPushEndpointOwned
		if errors.As(err, &owned) {
			return nil, huma.Error409Conflict(err.Error())
		}
		var invalidSession notifications.ErrWebPushSessionInvalid
		if errors.As(err, &invalidSession) {
			return nil, huma.Error403Forbidden(err.Error())
		}
		return nil, huma.Error422UnprocessableEntity(err.Error())
	}
	if err := s.Commit(); err != nil {
		return nil, err
	}
	return &webPushSubscriptionBody{Body: webPushSubscriptionOutput{
		ID: subscription.ID, DeviceID: subscription.DeviceID, Created: subscription.Created, Updated: subscription.Updated,
	}}, nil
}

func webPushSubscriptionDelete(ctx context.Context, in *struct {
	DeviceID string `path:"device_id"`
}) (*emptyBody, error) {
	userID, sessionID, err := webPushSession(ctx)
	if err != nil {
		return nil, err
	}
	s := db.NewSession()
	defer s.Close()
	if err := notifications.DeleteWebPushSubscription(s, userID, sessionID, in.DeviceID); err != nil {
		_ = s.Rollback()
		return nil, err
	}
	if err := s.Commit(); err != nil {
		return nil, err
	}
	return &emptyBody{}, nil
}

func webPushSubscriptionTest(ctx context.Context, in *struct {
	DeviceID string `path:"device_id"`
}) (*webPushTestBody, error) {
	userID, sessionID, err := webPushSession(ctx)
	if err != nil {
		return nil, err
	}
	s := db.NewSession()
	defer s.Close()
	u, err := user.GetUserByID(s, userID)
	if err != nil {
		return nil, translateDomainError(err)
	}
	err = notifications.SendWebPushTest(ctx, s, userID, sessionID, in.DeviceID, notifications.WebPushMessage{
		Title: "Vikunja",
		Body:  i18n.T(u.Language, "notifications.web_push.test"),
		URL:   "/",
	})
	if err != nil {
		var invalidSubscription notifications.ErrWebPushSubscriptionInvalid
		if errors.As(err, &invalidSubscription) {
			if commitErr := s.Commit(); commitErr != nil {
				return nil, commitErr
			}
			return nil, huma.NewError(http.StatusGone, err.Error())
		}
		_ = s.Rollback()
		return nil, huma.Error502BadGateway(err.Error())
	}
	_ = s.Rollback()
	out := &webPushTestBody{}
	out.Body.Accepted = true
	return out, nil
}
