name: Bug Report
description: Found something you weren't expecting? Report it here!
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Chaku is a fork of [Vikunja](https://vikunja.io). If your bug exists in upstream Vikunja as well, please consider reporting it there too.
  - type: markdown
    attributes:
      value: |
        Please fill out this issue template to report a bug.

        1. Make sure you are using the latest release and
           take a moment to check that your issue hasn't been reported before.
        2. Please give all relevant information below for bug reports, because
           incomplete details will be handled as an invalid report and closed.
  - type: checkboxes
    id: searched
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched for existing open or closed issue reports with the same problem.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your issue here, with a URL if you were able to reproduce the issue (see below).
  - type: input
    id: version
    attributes:
      label: Chaku Version
      description: Chaku version (or commit reference) of your instance
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser and version
      description: If your issue is related to a frontend problem, please provide the browser and version you used to reproduce it.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If this issue involves the Web Interface, please provide one or more screenshots
