// Code generated by yaegi extract. DO NOT EDIT.

package yaegi_symbols

import "reflect"

// Symbols contains all Vikunja and third-party symbols for use with yaegi's Use() method.
var Symbols = map[string]map[string]reflect.Value{}
