// Code generated by 'yaegi extract code.vikunja.io/api/pkg/log'. DO NOT EDIT.

package yaegi_symbols

import (
	"reflect"

	"code.vikunja.io/api/pkg/log"
)

func init() {
	Symbols["code.vikunja.io/api/pkg/log/log"] = map[string]reflect.Value{
		"ConfigureStandardLogger": reflect.ValueOf(log.ConfigureStandardLogger),
		"Critical":               reflect.ValueOf(log.Critical),
		"Criticalf":              reflect.ValueOf(log.Criticalf),
		"Debug":                  reflect.ValueOf(log.Debug),
		"Debugf":                 reflect.ValueOf(log.Debugf),
		"Error":                  reflect.ValueOf(log.Error),
		"Errorf":                 reflect.ValueOf(log.Errorf),
		"Fatal":                  reflect.ValueOf(log.Fatal),
		"Fatalf":                 reflect.ValueOf(log.Fatalf),
		"GetLogger":              reflect.ValueOf(log.GetLogger),
		"Info":                   reflect.ValueOf(log.Info),
		"Infof":                  reflect.ValueOf(log.Infof),
		"InitLogger":             reflect.ValueOf(log.InitLogger),
		"NewEchoLogger":          reflect.ValueOf(log.NewEchoLogger),
		"NewHTTPLogger":          reflect.ValueOf(log.NewHTTPLogger),
		"NewMailLogger":          reflect.ValueOf(log.NewMailLogger),
		"NewWatermillLogger":     reflect.ValueOf(log.NewWatermillLogger),
		"NewXormLogger":          reflect.ValueOf(log.NewXormLogger),
		"Warning":                reflect.ValueOf(log.Warning),
		"Warningf":               reflect.ValueOf(log.Warningf),

		// type definitions
		"MailLogger":      reflect.ValueOf((*log.MailLogger)(nil)),
		"NoopBackend":     reflect.ValueOf((*log.NoopBackend)(nil)),
		"WatermillLogger": reflect.ValueOf((*log.WatermillLogger)(nil)),
		"XormLogger":      reflect.ValueOf((*log.XormLogger)(nil)),
	}
}
