
package yaegi_symbols

import (
	"go/constant"
	"go/token"
	"code.vikunja.io/api/pkg/user"
	"reflect"
)

func init() {
	Symbols["code.vikunja.io/api/pkg/user/user"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CancelDeletion": reflect.ValueOf(user.CancelDeletion),
			"CheckUserCredentials": reflect.ValueOf(user.CheckUserCredentials),
			"CheckUserPassword": reflect.ValueOf(user.CheckUserPassword),
			"ConfirmDeletion": reflect.ValueOf(user.ConfirmDeletion),
			"ConfirmEmail": reflect.ValueOf(user.ConfirmEmail),
			"CreateUser": reflect.ValueOf(user.CreateUser),
			"DeleteCaldavTokenByID": reflect.ValueOf(user.DeleteCaldavTokenByID),
			"DisableTOTP": reflect.ValueOf(user.DisableTOTP),
			"EnableTOTP": reflect.ValueOf(user.EnableTOTP),
			"EnrollTOTP": reflect.ValueOf(user.EnrollTOTP),
			"ErrCodeAccountDisabled": reflect.ValueOf(constant.MakeFromLiteral("1020", token.INT, 0)),
			"ErrCodeAccountIsNotLocal": reflect.ValueOf(constant.MakeFromLiteral("1021", token.INT, 0)),
			"ErrCodeCouldNotGetUserID": reflect.ValueOf(constant.MakeFromLiteral("1006", token.INT, 0)),
			"ErrCodeEmailNotConfirmed": reflect.ValueOf(constant.MakeFromLiteral("1012", token.INT, 0)),
			"ErrCodeEmptyNewPassword": reflect.ValueOf(constant.MakeFromLiteral("1013", token.INT, 0)),
			"ErrCodeEmptyOldPassword": reflect.ValueOf(constant.MakeFromLiteral("1014", token.INT, 0)),
			"ErrCodeInvalidAvatarProvider": reflect.ValueOf(constant.MakeFromLiteral("1018", token.INT, 0)),
			"ErrCodeInvalidClaimData": reflect.ValueOf(constant.MakeFromLiteral("1024", token.INT, 0)),
			"ErrCodeInvalidEmailConfirmToken": reflect.ValueOf(constant.MakeFromLiteral("1010", token.INT, 0)),
			"ErrCodeInvalidPasswordResetToken": reflect.ValueOf(constant.MakeFromLiteral("1009", token.INT, 0)),
			"ErrCodeInvalidTOTPPasscode": reflect.ValueOf(constant.MakeFromLiteral("1017", token.INT, 0)),
			"ErrCodeMustNotBeLinkShare": reflect.ValueOf(constant.MakeFromLiteral("1023", token.INT, 0)),
			"ErrCodeNoOpenIDEmailProvided": reflect.ValueOf(constant.MakeFromLiteral("1019", token.INT, 0)),
			"ErrCodeNoPasswordResetToken": reflect.ValueOf(constant.MakeFromLiteral("1008", token.INT, 0)),
			"ErrCodeNoUsernamePassword": reflect.ValueOf(constant.MakeFromLiteral("1004", token.INT, 0)),
			"ErrCodeOpenIDCustomScopeMalformed": reflect.ValueOf(constant.MakeFromLiteral("1022", token.INT, 0)),
			"ErrCodeTOTPAlreadyEnabled": reflect.ValueOf(constant.MakeFromLiteral("1015", token.INT, 0)),
			"ErrCodeTOTPNotEnabled": reflect.ValueOf(constant.MakeFromLiteral("1016", token.INT, 0)),
			"ErrCodeUserDoesNotExist": reflect.ValueOf(constant.MakeFromLiteral("1005", token.INT, 0)),
			"ErrCodeUsernameMustNotContainSpaces": reflect.ValueOf(constant.MakeFromLiteral("1022", token.INT, 0)),
			"ErrCodeWrongUsernameOrPassword": reflect.ValueOf(constant.MakeFromLiteral("1011", token.INT, 0)),
			"ErrorCodeInvalidDeletionToken": reflect.ValueOf(constant.MakeFromLiteral("1028", token.INT, 0)),
			"ErrorCodeInvalidTimezone": reflect.ValueOf(constant.MakeFromLiteral("1025", token.INT, 0)),
			"ErrorCodeInvalidUserContext": reflect.ValueOf(constant.MakeFromLiteral("1027", token.INT, 0)),
			"ErrorCodeTokenUserMismatch": reflect.ValueOf(constant.MakeFromLiteral("1029", token.INT, 0)),
			"ErrorCodeUserEmailExists": reflect.ValueOf(constant.MakeFromLiteral("1002", token.INT, 0)),
			"ErrorCodeUsernameExists": reflect.ValueOf(constant.MakeFromLiteral("1001", token.INT, 0)),
			"ErrorCodeUsernameReserved": reflect.ValueOf(constant.MakeFromLiteral("1026", token.INT, 0)),
			"GenerateNewCaldavToken": reflect.ValueOf(user.GenerateNewCaldavToken),
			"GetCaldavTokens": reflect.ValueOf(user.GetCaldavTokens),
			"GetCurrentUser": reflect.ValueOf(user.GetCurrentUser),
			"GetCurrentUserFromDB": reflect.ValueOf(user.GetCurrentUserFromDB),
			"GetFromAuth": reflect.ValueOf(user.GetFromAuth),
			"GetTOTPForUser": reflect.ValueOf(user.GetTOTPForUser),
			"GetTOTPQrCodeForUser": reflect.ValueOf(user.GetTOTPQrCodeForUser),
			"GetTables": reflect.ValueOf(user.GetTables),
			"GetUserByID": reflect.ValueOf(user.GetUserByID),
			"GetUserByUsername": reflect.ValueOf(user.GetUserByUsername),
			"GetUserFromClaims": reflect.ValueOf(user.GetUserFromClaims),
			"GetUserWithEmail": reflect.ValueOf(user.GetUserWithEmail),
			"GetUsersByCond": reflect.ValueOf(user.GetUsersByCond),
			"GetUsersByIDs": reflect.ValueOf(user.GetUsersByIDs),
			"GetUsersByUsername": reflect.ValueOf(user.GetUsersByUsername),
			"HandleFailedTOTPAuth": reflect.ValueOf(user.HandleFailedTOTPAuth),
			"HashPassword": reflect.ValueOf(user.HashPassword),
			"InitTests": reflect.ValueOf(user.InitTests),
			"IsErrAccountDisabled": reflect.ValueOf(user.IsErrAccountDisabled),
			"IsErrAccountIsNotLocal": reflect.ValueOf(user.IsErrAccountIsNotLocal),
			"IsErrCouldNotGetUserID": reflect.ValueOf(user.IsErrCouldNotGetUserID),
			"IsErrEmailNotConfirmed": reflect.ValueOf(user.IsErrEmailNotConfirmed),
			"IsErrEmptyNewPassword": reflect.ValueOf(user.IsErrEmptyNewPassword),
			"IsErrEmptyOldPassword": reflect.ValueOf(user.IsErrEmptyOldPassword),
			"IsErrInvalidAvatarProvider": reflect.ValueOf(user.IsErrInvalidAvatarProvider),
			"IsErrInvalidClaimData": reflect.ValueOf(user.IsErrInvalidClaimData),
			"IsErrInvalidDeletionToken": reflect.ValueOf(user.IsErrInvalidDeletionToken),
			"IsErrInvalidEmailConfirmToken": reflect.ValueOf(user.IsErrInvalidEmailConfirmToken),
			"IsErrInvalidPasswordResetToken": reflect.ValueOf(user.IsErrInvalidPasswordResetToken),
			"IsErrInvalidTOTPPasscode": reflect.ValueOf(user.IsErrInvalidTOTPPasscode),
			"IsErrInvalidTimezone": reflect.ValueOf(user.IsErrInvalidTimezone),
			"IsErrInvalidUserContext": reflect.ValueOf(user.IsErrInvalidUserContext),
			"IsErrMustNotBeLinkShare": reflect.ValueOf(user.IsErrMustNotBeLinkShare),
			"IsErrNoEmailProvided": reflect.ValueOf(user.IsErrNoEmailProvided),
			"IsErrNoPasswordResetToken": reflect.ValueOf(user.IsErrNoPasswordResetToken),
			"IsErrNoUsernamePassword": reflect.ValueOf(user.IsErrNoUsernamePassword),
			"IsErrOpenIDCustomScopeMalformed": reflect.ValueOf(user.IsErrOpenIDCustomScopeMalformed),
			"IsErrTOTPAlreadyEnabled": reflect.ValueOf(user.IsErrTOTPAlreadyEnabled),
			"IsErrTOTPNotEnabled": reflect.ValueOf(user.IsErrTOTPNotEnabled),
			"IsErrTokenUserMismatch": reflect.ValueOf(user.IsErrTokenUserMismatch),
			"IsErrUserDoesNotExist": reflect.ValueOf(user.IsErrUserDoesNotExist),
			"IsErrUserEmailExists": reflect.ValueOf(user.IsErrUserEmailExists),
			"IsErrUsernameExists": reflect.ValueOf(user.IsErrUsernameExists),
			"IsErrUsernameMustNotContainSpaces": reflect.ValueOf(user.IsErrUsernameMustNotContainSpaces),
			"IsErrUsernameReserved": reflect.ValueOf(user.IsErrUsernameReserved),
			"IsErrWrongUsernameOrPassword": reflect.ValueOf(user.IsErrWrongUsernameOrPassword),
			"IssuerLDAP": reflect.ValueOf(constant.MakeFromLiteral("\"ldap\"", token.STRING, 0)),
			"IssuerLocal": reflect.ValueOf(constant.MakeFromLiteral("\"local\"", token.STRING, 0)),
			"ListAllUsers": reflect.ValueOf(user.ListAllUsers),
			"ListUsers": reflect.ValueOf(user.ListUsers),
			"RegisterDeletionNotificationCron": reflect.ValueOf(user.RegisterDeletionNotificationCron),
			"RegisterListeners": reflect.ValueOf(user.RegisterListeners),
			"RegisterTokenCleanupCron": reflect.ValueOf(user.RegisterTokenCleanupCron),
			"RequestDeletion": reflect.ValueOf(user.RequestDeletion),
			"RequestUserPasswordResetToken": reflect.ValueOf(user.RequestUserPasswordResetToken),
			"RequestUserPasswordResetTokenByEmail": reflect.ValueOf(user.RequestUserPasswordResetTokenByEmail),
			"ResetPassword": reflect.ValueOf(user.ResetPassword),
			"ScheduleDeletion": reflect.ValueOf(user.ScheduleDeletion),
			"SetUserStatus": reflect.ValueOf(user.SetUserStatus),
			"StatusActive": reflect.ValueOf(user.StatusActive),
			"StatusDisabled": reflect.ValueOf(user.StatusDisabled),
			"StatusEmailConfirmationRequired": reflect.ValueOf(user.StatusEmailConfirmationRequired),
			"TOTPEnabledForUser": reflect.ValueOf(user.TOTPEnabledForUser),
			"TokenAccountDeletion": reflect.ValueOf(user.TokenAccountDeletion),
			"TokenCaldavAuth": reflect.ValueOf(user.TokenCaldavAuth),
			"TokenEmailConfirm": reflect.ValueOf(user.TokenEmailConfirm),
			"TokenPasswordReset": reflect.ValueOf(user.TokenPasswordReset),
			"TokenUnknown": reflect.ValueOf(user.TokenUnknown),
			"UpdateEmail": reflect.ValueOf(user.UpdateEmail),
			"UpdateUser": reflect.ValueOf(user.UpdateUser),
			"UpdateUserPassword": reflect.ValueOf(user.UpdateUserPassword),
			"ValidateTOTPPasscode": reflect.ValueOf(user.ValidateTOTPPasscode),
			
		// type definitions
		"APIUserPassword": reflect.ValueOf((*user.APIUserPassword)(nil)),
		"AccountDeletedNotification": reflect.ValueOf((*user.AccountDeletedNotification)(nil)),
		"AccountDeletionConfirmNotification": reflect.ValueOf((*user.AccountDeletionConfirmNotification)(nil)),
		"AccountDeletionNotification": reflect.ValueOf((*user.AccountDeletionNotification)(nil)),
		"CreatedEvent": reflect.ValueOf((*user.CreatedEvent)(nil)),
		"EmailConfirm": reflect.ValueOf((*user.EmailConfirm)(nil)),
		"EmailConfirmNotification": reflect.ValueOf((*user.EmailConfirmNotification)(nil)),
		"EmailUpdate": reflect.ValueOf((*user.EmailUpdate)(nil)),
		"ErrAccountDisabled": reflect.ValueOf((*user.ErrAccountDisabled)(nil)),
		"ErrAccountIsNotLocal": reflect.ValueOf((*user.ErrAccountIsNotLocal)(nil)),
		"ErrCouldNotGetUserID": reflect.ValueOf((*user.ErrCouldNotGetUserID)(nil)),
		"ErrEmailNotConfirmed": reflect.ValueOf((*user.ErrEmailNotConfirmed)(nil)),
		"ErrEmptyNewPassword": reflect.ValueOf((*user.ErrEmptyNewPassword)(nil)),
		"ErrEmptyOldPassword": reflect.ValueOf((*user.ErrEmptyOldPassword)(nil)),
		"ErrInvalidAvatarProvider": reflect.ValueOf((*user.ErrInvalidAvatarProvider)(nil)),
		"ErrInvalidClaimData": reflect.ValueOf((*user.ErrInvalidClaimData)(nil)),
		"ErrInvalidDeletionToken": reflect.ValueOf((*user.ErrInvalidDeletionToken)(nil)),
		"ErrInvalidEmailConfirmToken": reflect.ValueOf((*user.ErrInvalidEmailConfirmToken)(nil)),
		"ErrInvalidPasswordResetToken": reflect.ValueOf((*user.ErrInvalidPasswordResetToken)(nil)),
		"ErrInvalidTOTPPasscode": reflect.ValueOf((*user.ErrInvalidTOTPPasscode)(nil)),
		"ErrInvalidTimezone": reflect.ValueOf((*user.ErrInvalidTimezone)(nil)),
		"ErrInvalidUserContext": reflect.ValueOf((*user.ErrInvalidUserContext)(nil)),
		"ErrMustNotBeLinkShare": reflect.ValueOf((*user.ErrMustNotBeLinkShare)(nil)),
		"ErrNoOpenIDEmailProvided": reflect.ValueOf((*user.ErrNoOpenIDEmailProvided)(nil)),
		"ErrNoPasswordResetToken": reflect.ValueOf((*user.ErrNoPasswordResetToken)(nil)),
		"ErrNoUsernamePassword": reflect.ValueOf((*user.ErrNoUsernamePassword)(nil)),
		"ErrOpenIDCustomScopeMalformed": reflect.ValueOf((*user.ErrOpenIDCustomScopeMalformed)(nil)),
		"ErrTOTPAlreadyEnabled": reflect.ValueOf((*user.ErrTOTPAlreadyEnabled)(nil)),
		"ErrTOTPNotEnabled": reflect.ValueOf((*user.ErrTOTPNotEnabled)(nil)),
		"ErrTokenUserMismatch": reflect.ValueOf((*user.ErrTokenUserMismatch)(nil)),
		"ErrUserDoesNotExist": reflect.ValueOf((*user.ErrUserDoesNotExist)(nil)),
		"ErrUserEmailExists": reflect.ValueOf((*user.ErrUserEmailExists)(nil)),
		"ErrUsernameExists": reflect.ValueOf((*user.ErrUsernameExists)(nil)),
		"ErrUsernameMustNotContainSpaces": reflect.ValueOf((*user.ErrUsernameMustNotContainSpaces)(nil)),
		"ErrUsernameReserved": reflect.ValueOf((*user.ErrUsernameReserved)(nil)),
		"ErrWrongUsernameOrPassword": reflect.ValueOf((*user.ErrWrongUsernameOrPassword)(nil)),
		"FailedLoginAttemptNotification": reflect.ValueOf((*user.FailedLoginAttemptNotification)(nil)),
		"IncreaseUserCounter": reflect.ValueOf((*user.IncreaseUserCounter)(nil)),
		"InvalidTOTPNotification": reflect.ValueOf((*user.InvalidTOTPNotification)(nil)),
		"Login": reflect.ValueOf((*user.Login)(nil)),
		"PasswordAccountLockedAfterInvalidTOTPNotification": reflect.ValueOf((*user.PasswordAccountLockedAfterInvalidTOTPNotification)(nil)),
		"PasswordChangedNotification": reflect.ValueOf((*user.PasswordChangedNotification)(nil)),
		"PasswordReset": reflect.ValueOf((*user.PasswordReset)(nil)),
		"PasswordTokenRequest": reflect.ValueOf((*user.PasswordTokenRequest)(nil)),
		"ProjectUserOpts": reflect.ValueOf((*user.ProjectUserOpts)(nil)),
		"ResetPasswordNotification": reflect.ValueOf((*user.ResetPasswordNotification)(nil)),
		"Status": reflect.ValueOf((*user.Status)(nil)),
		"TOTP": reflect.ValueOf((*user.TOTP)(nil)),
		"TOTPPasscode": reflect.ValueOf((*user.TOTPPasscode)(nil)),
		"Token": reflect.ValueOf((*user.Token)(nil)),
		"TokenKind": reflect.ValueOf((*user.TokenKind)(nil)),
		"User": reflect.ValueOf((*user.User)(nil)),
		
	}
}
