// Code generated by 'yaegi extract code.vikunja.io/api/pkg/events'. DO NOT EDIT.

package yaegi_symbols

import (
	"reflect"

	"code.vikunja.io/api/pkg/events"
	"github.com/ThreeDotsLabs/watermill/message"
)

func init() {
	Symbols["code.vikunja.io/api/pkg/events/events"] = map[string]reflect.Value{
		"AssertDispatched":     reflect.ValueOf(events.AssertDispatched),
		"ClearDispatchedEvents": reflect.ValueOf(events.ClearDispatchedEvents),
		"CountDispatchedEvents": reflect.ValueOf(events.CountDispatchedEvents),
		"Dispatch":             reflect.ValueOf(events.Dispatch),
		"Fake":                 reflect.ValueOf(events.Fake),
		"InitEvents":           reflect.ValueOf(events.InitEvents),
		"RegisterListener":     reflect.ValueOf(events.RegisterListener),
		"TestListener":         reflect.ValueOf(events.TestListener),

		// type definitions
		"Event":    reflect.ValueOf((*events.Event)(nil)),
		"Listener": reflect.ValueOf((*events.Listener)(nil)),

		// interface wrapper definitions
		"_Event":    reflect.ValueOf((*_code_vikunja_io_api_pkg_events_Event)(nil)),
		"_Listener": reflect.ValueOf((*_code_vikunja_io_api_pkg_events_Listener)(nil)),
	}
}

type _code_vikunja_io_api_pkg_events_Event struct {
	IValue interface{}
	WName  func() string
}

func (W _code_vikunja_io_api_pkg_events_Event) Name() string { return W.WName() }

type _code_vikunja_io_api_pkg_events_Listener struct {
	IValue  interface{}
	WHandle func(msg *message.Message) error
	WName   func() string
}

func (W _code_vikunja_io_api_pkg_events_Listener) Handle(msg *message.Message) error {
	return W.WHandle(msg)
}
func (W _code_vikunja_io_api_pkg_events_Listener) Name() string { return W.WName() }
