// Code generated by 'yaegi extract code.vikunja.io/api/pkg/db'. DO NOT EDIT.

package yaegi_symbols

import (
	"reflect"

	"code.vikunja.io/api/pkg/db"
)

func init() {
	Symbols["code.vikunja.io/api/pkg/db/db"] = map[string]reflect.Value{
		"AssertCount":                   reflect.ValueOf(db.AssertCount),
		"AssertExists":                  reflect.ValueOf(db.AssertExists),
		"AssertMissing":                 reflect.ValueOf(db.AssertMissing),
		"CreateDBEngine":               reflect.ValueOf(db.CreateDBEngine),
		"CreateParadeDBIndexes":        reflect.ValueOf(db.CreateParadeDBIndexes),
		"CreateTestEngine":             reflect.ValueOf(db.CreateTestEngine),
		"Dump":                         reflect.ValueOf(db.Dump),
		"GetDialect":                   reflect.ValueOf(db.GetDialect),
		"ILIKE":                        reflect.ValueOf(db.ILIKE),
		"InitFixtures":                 reflect.ValueOf(db.InitFixtures),
		"InitTestFixtures":             reflect.ValueOf(db.InitTestFixtures),
		"IsMySQLDuplicateEntryError":   reflect.ValueOf(db.IsMySQLDuplicateEntryError),
		"IsUniqueConstraintError":      reflect.ValueOf(db.IsUniqueConstraintError),
		"LoadAndAssertFixtures":        reflect.ValueOf(db.LoadAndAssertFixtures),
		"LoadFixtures":                 reflect.ValueOf(db.LoadFixtures),
		"MultiFieldSearch":             reflect.ValueOf(db.MultiFieldSearch),
		"MultiFieldSearchWithTableAlias": reflect.ValueOf(db.MultiFieldSearchWithTableAlias),
		"NewSession":                   reflect.ValueOf(db.NewSession),
		"ParadeDBAvailable":            reflect.ValueOf(db.ParadeDBAvailable),
		"Restore":                      reflect.ValueOf(db.Restore),
		"RestoreAndTruncate":           reflect.ValueOf(db.RestoreAndTruncate),
		"Type":                         reflect.ValueOf(db.Type),
		"WipeEverything":               reflect.ValueOf(db.WipeEverything),
	}
}
