// Code generated by 'yaegi extract src.techknowlogick.com/xormigrate'. DO NOT EDIT.

package yaegi_symbols

import (
	"reflect"
	"src.techknowlogick.com/xormigrate"
)

func init() {
	Symbols["src.techknowlogick.com/xormigrate/xormigrate"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrMigrationIDDoesNotExist": reflect.ValueOf(&xormigrate.ErrMigrationIDDoesNotExist).Elem(),
		"ErrMissingID":               reflect.ValueOf(&xormigrate.ErrMissingID).Elem(),
		"ErrNoMigrationDefined":      reflect.ValueOf(&xormigrate.ErrNoMigrationDefined).Elem(),
		"ErrNoRunMigration":          reflect.ValueOf(&xormigrate.ErrNoRunMigration).Elem(),
		"ErrRollbackImpossible":      reflect.ValueOf(&xormigrate.ErrRollbackImpossible).Elem(),
		"New":                        reflect.ValueOf(xormigrate.New),

		// type definitions
		"DuplicatedIDError":   reflect.ValueOf((*xormigrate.DuplicatedIDError)(nil)),
		"InitSchemaFunc":      reflect.ValueOf((*xormigrate.InitSchemaFunc)(nil)),
		"LoggerInterface":     reflect.ValueOf((*xormigrate.LoggerInterface)(nil)),
		"MigrateFunc":         reflect.ValueOf((*xormigrate.MigrateFunc)(nil)),
		"MigrateFuncSession":  reflect.ValueOf((*xormigrate.MigrateFuncSession)(nil)),
		"Migration":           reflect.ValueOf((*xormigrate.Migration)(nil)),
		"ReservedIDError":     reflect.ValueOf((*xormigrate.ReservedIDError)(nil)),
		"RollbackFunc":        reflect.ValueOf((*xormigrate.RollbackFunc)(nil)),
		"RollbackFuncSession": reflect.ValueOf((*xormigrate.RollbackFuncSession)(nil)),
		"Xormigrate":          reflect.ValueOf((*xormigrate.Xormigrate)(nil)),
		"XormigrateLogger":    reflect.ValueOf((*xormigrate.XormigrateLogger)(nil)),

		// interface wrapper definitions
		"_LoggerInterface": reflect.ValueOf((*_src_techknowlogick_com_xormigrate_LoggerInterface)(nil)),
	}
}

// _src_techknowlogick_com_xormigrate_LoggerInterface is an interface wrapper for LoggerInterface type
type _src_techknowlogick_com_xormigrate_LoggerInterface struct {
	IValue  interface{}
	WDebug  func(v ...interface{})
	WDebugf func(format string, v ...interface{})
	WError  func(v ...interface{})
	WErrorf func(format string, v ...interface{})
	WInfo   func(v ...interface{})
	WInfof  func(format string, v ...interface{})
	WWarn   func(v ...interface{})
	WWarnf  func(format string, v ...interface{})
}

func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Debug(v ...interface{}) {
	W.WDebug(v...)
}
func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Debugf(format string, v ...interface{}) {
	W.WDebugf(format, v...)
}
func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Error(v ...interface{}) {
	W.WError(v...)
}
func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Errorf(format string, v ...interface{}) {
	W.WErrorf(format, v...)
}
func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Info(v ...interface{}) {
	W.WInfo(v...)
}
func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Infof(format string, v ...interface{}) {
	W.WInfof(format, v...)
}
func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Warn(v ...interface{}) {
	W.WWarn(v...)
}
func (W _src_techknowlogick_com_xormigrate_LoggerInterface) Warnf(format string, v ...interface{}) {
	W.WWarnf(format, v...)
}
