// Code generated by 'yaegi extract xorm.io/xorm'. DO NOT EDIT.

package yaegi_symbols

import (
	"context"
	"database/sql"
	"reflect"
	"time"
	"xorm.io/xorm"
	"xorm.io/xorm/caches"
	"xorm.io/xorm/contexts"
	"xorm.io/xorm/dialects"
	"xorm.io/xorm/log"
	"xorm.io/xorm/names"
	"xorm.io/xorm/schemas"
)

func init() {
	Symbols["xorm.io/xorm/xorm"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrCacheFailed":            reflect.ValueOf(&xorm.ErrCacheFailed).Elem(),
		"ErrConditionType":          reflect.ValueOf(&xorm.ErrConditionType).Elem(),
		"ErrNeedDeletedCond":        reflect.ValueOf(&xorm.ErrNeedDeletedCond).Elem(),
		"ErrNoColumnsTobeUpdated":   reflect.ValueOf(&xorm.ErrNoColumnsTobeUpdated).Elem(),
		"ErrNoElementsOnSlice":      reflect.ValueOf(&xorm.ErrNoElementsOnSlice).Elem(),
		"ErrNotExist":               reflect.ValueOf(&xorm.ErrNotExist).Elem(),
		"ErrObjectIsNil":            reflect.ValueOf(&xorm.ErrObjectIsNil).Elem(),
		"ErrParamsType":             reflect.ValueOf(&xorm.ErrParamsType).Elem(),
		"ErrPtrSliceType":           reflect.ValueOf(&xorm.ErrPtrSliceType).Elem(),
		"ErrTableNotFound":          reflect.ValueOf(&xorm.ErrTableNotFound).Elem(),
		"ErrUnSupportedType":        reflect.ValueOf(&xorm.ErrUnSupportedType).Elem(),
		"LeastConnPolicy":           reflect.ValueOf(xorm.LeastConnPolicy),
		"NewEngine":                 reflect.ValueOf(xorm.NewEngine),
		"NewEngineGroup":            reflect.ValueOf(xorm.NewEngineGroup),
		"NewEngineWithDB":           reflect.ValueOf(xorm.NewEngineWithDB),
		"NewEngineWithDialectAndDB": reflect.ValueOf(xorm.NewEngineWithDialectAndDB),
		"NewEngineWithParams":       reflect.ValueOf(xorm.NewEngineWithParams),
		"ParseColumnsSchema":        reflect.ValueOf(xorm.ParseColumnsSchema),
		"RandomPolicy":              reflect.ValueOf(xorm.RandomPolicy),
		"RoundRobinPolicy":          reflect.ValueOf(xorm.RoundRobinPolicy),
		"SetDefaultJSONHandler":     reflect.ValueOf(xorm.SetDefaultJSONHandler),
		"WeightRandomPolicy":        reflect.ValueOf(xorm.WeightRandomPolicy),
		"WeightRoundRobinPolicy":    reflect.ValueOf(xorm.WeightRoundRobinPolicy),

		// type definitions
		"AfterDeleteProcessor":      reflect.ValueOf((*xorm.AfterDeleteProcessor)(nil)),
		"AfterInsertProcessor":      reflect.ValueOf((*xorm.AfterInsertProcessor)(nil)),
		"AfterLoadProcessor":        reflect.ValueOf((*xorm.AfterLoadProcessor)(nil)),
		"AfterLoadSessionProcessor": reflect.ValueOf((*xorm.AfterLoadSessionProcessor)(nil)),
		"AfterSetProcessor":         reflect.ValueOf((*xorm.AfterSetProcessor)(nil)),
		"AfterUpdateProcessor":      reflect.ValueOf((*xorm.AfterUpdateProcessor)(nil)),
		"BeforeDeleteProcessor":     reflect.ValueOf((*xorm.BeforeDeleteProcessor)(nil)),
		"BeforeInsertProcessor":     reflect.ValueOf((*xorm.BeforeInsertProcessor)(nil)),
		"BeforeSetProcessor":        reflect.ValueOf((*xorm.BeforeSetProcessor)(nil)),
		"BeforeUpdateProcessor":     reflect.ValueOf((*xorm.BeforeUpdateProcessor)(nil)),
		"Cell":                      reflect.ValueOf((*xorm.Cell)(nil)),
		"ColumnsSchema":             reflect.ValueOf((*xorm.ColumnsSchema)(nil)),
		"Engine":                    reflect.ValueOf((*xorm.Engine)(nil)),
		"EngineGroup":               reflect.ValueOf((*xorm.EngineGroup)(nil)),
		"EngineInterface":           reflect.ValueOf((*xorm.EngineInterface)(nil)),
		"ErrFieldIsNotExist":        reflect.ValueOf((*xorm.ErrFieldIsNotExist)(nil)),
		"ErrFieldIsNotValid":        reflect.ValueOf((*xorm.ErrFieldIsNotValid)(nil)),
		"GroupPolicy":               reflect.ValueOf((*xorm.GroupPolicy)(nil)),
		"GroupPolicyHandler":        reflect.ValueOf((*xorm.GroupPolicyHandler)(nil)),
		"Interface":                 reflect.ValueOf((*xorm.Interface)(nil)),
		"IterFunc":                  reflect.ValueOf((*xorm.IterFunc)(nil)),
		"QueryedField":              reflect.ValueOf((*xorm.QueryedField)(nil)),
		"Rows":                      reflect.ValueOf((*xorm.Rows)(nil)),
		"Session":                   reflect.ValueOf((*xorm.Session)(nil)),
		"SyncOptions":               reflect.ValueOf((*xorm.SyncOptions)(nil)),
		"SyncResult":                reflect.ValueOf((*xorm.SyncResult)(nil)),

		// interface wrapper definitions
		"_AfterDeleteProcessor":      reflect.ValueOf((*_xorm_io_xorm_AfterDeleteProcessor)(nil)),
		"_AfterInsertProcessor":      reflect.ValueOf((*_xorm_io_xorm_AfterInsertProcessor)(nil)),
		"_AfterLoadProcessor":        reflect.ValueOf((*_xorm_io_xorm_AfterLoadProcessor)(nil)),
		"_AfterLoadSessionProcessor": reflect.ValueOf((*_xorm_io_xorm_AfterLoadSessionProcessor)(nil)),
		"_AfterSetProcessor":         reflect.ValueOf((*_xorm_io_xorm_AfterSetProcessor)(nil)),
		"_AfterUpdateProcessor":      reflect.ValueOf((*_xorm_io_xorm_AfterUpdateProcessor)(nil)),
		"_BeforeDeleteProcessor":     reflect.ValueOf((*_xorm_io_xorm_BeforeDeleteProcessor)(nil)),
		"_BeforeInsertProcessor":     reflect.ValueOf((*_xorm_io_xorm_BeforeInsertProcessor)(nil)),
		"_BeforeSetProcessor":        reflect.ValueOf((*_xorm_io_xorm_BeforeSetProcessor)(nil)),
		"_BeforeUpdateProcessor":     reflect.ValueOf((*_xorm_io_xorm_BeforeUpdateProcessor)(nil)),
		"_EngineInterface":           reflect.ValueOf((*_xorm_io_xorm_EngineInterface)(nil)),
		"_GroupPolicy":               reflect.ValueOf((*_xorm_io_xorm_GroupPolicy)(nil)),
		"_Interface":                 reflect.ValueOf((*_xorm_io_xorm_Interface)(nil)),
	}
}

// _xorm_io_xorm_AfterDeleteProcessor is an interface wrapper for AfterDeleteProcessor type
type _xorm_io_xorm_AfterDeleteProcessor struct {
	IValue       interface{}
	WAfterDelete func()
}

func (W _xorm_io_xorm_AfterDeleteProcessor) AfterDelete() {
	W.WAfterDelete()
}

// _xorm_io_xorm_AfterInsertProcessor is an interface wrapper for AfterInsertProcessor type
type _xorm_io_xorm_AfterInsertProcessor struct {
	IValue       interface{}
	WAfterInsert func()
}

func (W _xorm_io_xorm_AfterInsertProcessor) AfterInsert() {
	W.WAfterInsert()
}

// _xorm_io_xorm_AfterLoadProcessor is an interface wrapper for AfterLoadProcessor type
type _xorm_io_xorm_AfterLoadProcessor struct {
	IValue     interface{}
	WAfterLoad func()
}

func (W _xorm_io_xorm_AfterLoadProcessor) AfterLoad() {
	W.WAfterLoad()
}

// _xorm_io_xorm_AfterLoadSessionProcessor is an interface wrapper for AfterLoadSessionProcessor type
type _xorm_io_xorm_AfterLoadSessionProcessor struct {
	IValue     interface{}
	WAfterLoad func(a0 *xorm.Session)
}

func (W _xorm_io_xorm_AfterLoadSessionProcessor) AfterLoad(a0 *xorm.Session) {
	W.WAfterLoad(a0)
}

// _xorm_io_xorm_AfterSetProcessor is an interface wrapper for AfterSetProcessor type
type _xorm_io_xorm_AfterSetProcessor struct {
	IValue    interface{}
	WAfterSet func(a0 string, a1 xorm.Cell)
}

func (W _xorm_io_xorm_AfterSetProcessor) AfterSet(a0 string, a1 xorm.Cell) {
	W.WAfterSet(a0, a1)
}

// _xorm_io_xorm_AfterUpdateProcessor is an interface wrapper for AfterUpdateProcessor type
type _xorm_io_xorm_AfterUpdateProcessor struct {
	IValue       interface{}
	WAfterUpdate func()
}

func (W _xorm_io_xorm_AfterUpdateProcessor) AfterUpdate() {
	W.WAfterUpdate()
}

// _xorm_io_xorm_BeforeDeleteProcessor is an interface wrapper for BeforeDeleteProcessor type
type _xorm_io_xorm_BeforeDeleteProcessor struct {
	IValue        interface{}
	WBeforeDelete func()
}

func (W _xorm_io_xorm_BeforeDeleteProcessor) BeforeDelete() {
	W.WBeforeDelete()
}

// _xorm_io_xorm_BeforeInsertProcessor is an interface wrapper for BeforeInsertProcessor type
type _xorm_io_xorm_BeforeInsertProcessor struct {
	IValue        interface{}
	WBeforeInsert func()
}

func (W _xorm_io_xorm_BeforeInsertProcessor) BeforeInsert() {
	W.WBeforeInsert()
}

// _xorm_io_xorm_BeforeSetProcessor is an interface wrapper for BeforeSetProcessor type
type _xorm_io_xorm_BeforeSetProcessor struct {
	IValue     interface{}
	WBeforeSet func(a0 string, a1 xorm.Cell)
}

func (W _xorm_io_xorm_BeforeSetProcessor) BeforeSet(a0 string, a1 xorm.Cell) {
	W.WBeforeSet(a0, a1)
}

// _xorm_io_xorm_BeforeUpdateProcessor is an interface wrapper for BeforeUpdateProcessor type
type _xorm_io_xorm_BeforeUpdateProcessor struct {
	IValue        interface{}
	WBeforeUpdate func()
}

func (W _xorm_io_xorm_BeforeUpdateProcessor) BeforeUpdate() {
	W.WBeforeUpdate()
}

// _xorm_io_xorm_EngineInterface is an interface wrapper for EngineInterface type
type _xorm_io_xorm_EngineInterface struct {
	IValue              interface{}
	WAddHook            func(hook contexts.Hook)
	WAfter              func(a0 func(any)) *xorm.Session
	WAlias              func(alias string) *xorm.Session
	WAllCols            func() *xorm.Session
	WAsc                func(colNames ...string) *xorm.Session
	WBefore             func(a0 func(any)) *xorm.Session
	WBufferSize         func(size int) *xorm.Session
	WCharset            func(charset string) *xorm.Session
	WClearCache         func(a0 ...any) error
	WCols               func(columns ...string) *xorm.Session
	WContext            func(a0 context.Context) *xorm.Session
	WCount              func(a0 ...any) (int64, error)
	WCreateIndexes      func(bean any) error
	WCreateTables       func(a0 ...any) error
	WCreateUniques      func(bean any) error
	WDBMetas            func() ([]*schemas.Table, error)
	WDBVersion          func() (*schemas.Version, error)
	WDecr               func(column string, arg ...any) *xorm.Session
	WDelete             func(a0 ...any) (int64, error)
	WDesc               func(a0 ...string) *xorm.Session
	WDialect            func() dialects.Dialect
	WDistinct           func(columns ...string) *xorm.Session
	WDriverName         func() string
	WDropIndexes        func(bean any) error
	WDropTables         func(a0 ...any) error
	WDumpAllToFile      func(fp string, tp ...schemas.DBType) error
	WEnableSessionID    func(a0 bool)
	WExec               func(sqlOrArgs ...any) (sql.Result, error)
	WExist              func(bean ...any) (bool, error)
	WFind               func(a0 any, a1 ...any) error
	WFindAndCount       func(a0 any, a1 ...any) (int64, error)
	WGet                func(a0 ...any) (bool, error)
	WGetCacher          func(a0 string) caches.Cacher
	WGetColumnMapper    func() names.Mapper
	WGetDefaultCacher   func() caches.Cacher
	WGetTZDatabase      func() *time.Location
	WGetTZLocation      func() *time.Location
	WGetTableMapper     func() names.Mapper
	WGroupBy            func(keys string) *xorm.Session
	WID                 func(a0 any) *xorm.Session
	WImportFile         func(fp string) ([]sql.Result, error)
	WIn                 func(a0 string, a1 ...any) *xorm.Session
	WIncr               func(column string, arg ...any) *xorm.Session
	WInsert             func(a0 ...any) (int64, error)
	WInsertOne          func(a0 any) (int64, error)
	WIsTableEmpty       func(bean any) (bool, error)
	WIsTableExist       func(beanOrTableName any) (bool, error)
	WIterate            func(a0 any, a1 xorm.IterFunc) error
	WJoin               func(joinOperator string, tablename any, condition any, args ...any) *xorm.Session
	WLimit              func(a0 int, a1 ...int) *xorm.Session
	WMapCacher          func(a0 any, a1 caches.Cacher) error
	WMustCols           func(columns ...string) *xorm.Session
	WNewSession         func() *xorm.Session
	WNoAutoCondition    func(a0 ...bool) *xorm.Session
	WNoAutoTime         func() *xorm.Session
	WNotIn              func(a0 string, a1 ...any) *xorm.Session
	WNullable           func(a0 ...string) *xorm.Session
	WOmit               func(columns ...string) *xorm.Session
	WOrderBy            func(order any, args ...any) *xorm.Session
	WPing               func() error
	WPrepare            func() *xorm.Session
	WQuery              func(sqlOrArgs ...any) (resultsSlice []map[string][]byte, err error)
	WQueryInterface     func(sqlOrArgs ...any) ([]map[string]any, error)
	WQueryString        func(sqlOrArgs ...any) ([]map[string]string, error)
	WQuote              func(a0 string) string
	WRows               func(bean any) (*xorm.Rows, error)
	WSQL                func(a0 any, a1 ...any) *xorm.Session
	WSelect             func(a0 string) *xorm.Session
	WSetCacher          func(a0 string, a1 caches.Cacher)
	WSetColumnMapper    func(a0 names.Mapper)
	WSetConnMaxLifetime func(a0 time.Duration)
	WSetDefaultCacher   func(a0 caches.Cacher)
	WSetExpr            func(a0 string, a1 any) *xorm.Session
	WSetLogLevel        func(a0 log.LogLevel)
	WSetLogger          func(logger any)
	WSetMapper          func(a0 names.Mapper)
	WSetMaxIdleConns    func(a0 int)
	WSetMaxOpenConns    func(a0 int)
	WSetQuotePolicy     func(a0 dialects.QuotePolicy)
	WSetSchema          func(a0 string)
	WSetTZDatabase      func(tz *time.Location)
	WSetTZLocation      func(tz *time.Location)
	WSetTableMapper     func(a0 names.Mapper)
	WSetTagIdentifier   func(a0 string)
	WShowSQL            func(show ...bool)
	WStoreEngine        func(storeEngine string) *xorm.Session
	WSum                func(bean any, colName string) (float64, error)
	WSumInt             func(bean any, colName string) (int64, error)
	WSums               func(bean any, colNames ...string) ([]float64, error)
	WSumsInt            func(bean any, colNames ...string) ([]int64, error)
	WSync               func(a0 ...any) error
	WSync2              func(a0 ...any) error
	WSyncWithOptions    func(a0 xorm.SyncOptions, a1 ...any) (*xorm.SyncResult, error)
	WTable              func(tableNameOrBean any) *xorm.Session
	WTableInfo          func(bean any) (*schemas.Table, error)
	WTableName          func(a0 any, a1 ...bool) string
	WTruncate           func(a0 ...any) (int64, error)
	WUnMapType          func(a0 reflect.Type)
	WUnscoped           func() *xorm.Session
	WUpdate             func(bean any, condiBeans ...any) (int64, error)
	WUseBool            func(a0 ...string) *xorm.Session
	WWhere              func(a0 any, a1 ...any) *xorm.Session
}

func (W _xorm_io_xorm_EngineInterface) AddHook(hook contexts.Hook) {
	W.WAddHook(hook)
}
func (W _xorm_io_xorm_EngineInterface) After(a0 func(any)) *xorm.Session {
	return W.WAfter(a0)
}
func (W _xorm_io_xorm_EngineInterface) Alias(alias string) *xorm.Session {
	return W.WAlias(alias)
}
func (W _xorm_io_xorm_EngineInterface) AllCols() *xorm.Session {
	return W.WAllCols()
}
func (W _xorm_io_xorm_EngineInterface) Asc(colNames ...string) *xorm.Session {
	return W.WAsc(colNames...)
}
func (W _xorm_io_xorm_EngineInterface) Before(a0 func(any)) *xorm.Session {
	return W.WBefore(a0)
}
func (W _xorm_io_xorm_EngineInterface) BufferSize(size int) *xorm.Session {
	return W.WBufferSize(size)
}
func (W _xorm_io_xorm_EngineInterface) Charset(charset string) *xorm.Session {
	return W.WCharset(charset)
}
func (W _xorm_io_xorm_EngineInterface) ClearCache(a0 ...any) error {
	return W.WClearCache(a0...)
}
func (W _xorm_io_xorm_EngineInterface) Cols(columns ...string) *xorm.Session {
	return W.WCols(columns...)
}
func (W _xorm_io_xorm_EngineInterface) Context(a0 context.Context) *xorm.Session {
	return W.WContext(a0)
}
func (W _xorm_io_xorm_EngineInterface) Count(a0 ...any) (int64, error) {
	return W.WCount(a0...)
}
func (W _xorm_io_xorm_EngineInterface) CreateIndexes(bean any) error {
	return W.WCreateIndexes(bean)
}
func (W _xorm_io_xorm_EngineInterface) CreateTables(a0 ...any) error {
	return W.WCreateTables(a0...)
}
func (W _xorm_io_xorm_EngineInterface) CreateUniques(bean any) error {
	return W.WCreateUniques(bean)
}
func (W _xorm_io_xorm_EngineInterface) DBMetas() ([]*schemas.Table, error) {
	return W.WDBMetas()
}
func (W _xorm_io_xorm_EngineInterface) DBVersion() (*schemas.Version, error) {
	return W.WDBVersion()
}
func (W _xorm_io_xorm_EngineInterface) Decr(column string, arg ...any) *xorm.Session {
	return W.WDecr(column, arg...)
}
func (W _xorm_io_xorm_EngineInterface) Delete(a0 ...any) (int64, error) {
	return W.WDelete(a0...)
}
func (W _xorm_io_xorm_EngineInterface) Desc(a0 ...string) *xorm.Session {
	return W.WDesc(a0...)
}
func (W _xorm_io_xorm_EngineInterface) Dialect() dialects.Dialect {
	return W.WDialect()
}
func (W _xorm_io_xorm_EngineInterface) Distinct(columns ...string) *xorm.Session {
	return W.WDistinct(columns...)
}
func (W _xorm_io_xorm_EngineInterface) DriverName() string {
	return W.WDriverName()
}
func (W _xorm_io_xorm_EngineInterface) DropIndexes(bean any) error {
	return W.WDropIndexes(bean)
}
func (W _xorm_io_xorm_EngineInterface) DropTables(a0 ...any) error {
	return W.WDropTables(a0...)
}
func (W _xorm_io_xorm_EngineInterface) DumpAllToFile(fp string, tp ...schemas.DBType) error {
	return W.WDumpAllToFile(fp, tp...)
}
func (W _xorm_io_xorm_EngineInterface) EnableSessionID(a0 bool) {
	W.WEnableSessionID(a0)
}
func (W _xorm_io_xorm_EngineInterface) Exec(sqlOrArgs ...any) (sql.Result, error) {
	return W.WExec(sqlOrArgs...)
}
func (W _xorm_io_xorm_EngineInterface) Exist(bean ...any) (bool, error) {
	return W.WExist(bean...)
}
func (W _xorm_io_xorm_EngineInterface) Find(a0 any, a1 ...any) error {
	return W.WFind(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) FindAndCount(a0 any, a1 ...any) (int64, error) {
	return W.WFindAndCount(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) Get(a0 ...any) (bool, error) {
	return W.WGet(a0...)
}
func (W _xorm_io_xorm_EngineInterface) GetCacher(a0 string) caches.Cacher {
	return W.WGetCacher(a0)
}
func (W _xorm_io_xorm_EngineInterface) GetColumnMapper() names.Mapper {
	return W.WGetColumnMapper()
}
func (W _xorm_io_xorm_EngineInterface) GetDefaultCacher() caches.Cacher {
	return W.WGetDefaultCacher()
}
func (W _xorm_io_xorm_EngineInterface) GetTZDatabase() *time.Location {
	return W.WGetTZDatabase()
}
func (W _xorm_io_xorm_EngineInterface) GetTZLocation() *time.Location {
	return W.WGetTZLocation()
}
func (W _xorm_io_xorm_EngineInterface) GetTableMapper() names.Mapper {
	return W.WGetTableMapper()
}
func (W _xorm_io_xorm_EngineInterface) GroupBy(keys string) *xorm.Session {
	return W.WGroupBy(keys)
}
func (W _xorm_io_xorm_EngineInterface) ID(a0 any) *xorm.Session {
	return W.WID(a0)
}
func (W _xorm_io_xorm_EngineInterface) ImportFile(fp string) ([]sql.Result, error) {
	return W.WImportFile(fp)
}
func (W _xorm_io_xorm_EngineInterface) In(a0 string, a1 ...any) *xorm.Session {
	return W.WIn(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) Incr(column string, arg ...any) *xorm.Session {
	return W.WIncr(column, arg...)
}
func (W _xorm_io_xorm_EngineInterface) Insert(a0 ...any) (int64, error) {
	return W.WInsert(a0...)
}
func (W _xorm_io_xorm_EngineInterface) InsertOne(a0 any) (int64, error) {
	return W.WInsertOne(a0)
}
func (W _xorm_io_xorm_EngineInterface) IsTableEmpty(bean any) (bool, error) {
	return W.WIsTableEmpty(bean)
}
func (W _xorm_io_xorm_EngineInterface) IsTableExist(beanOrTableName any) (bool, error) {
	return W.WIsTableExist(beanOrTableName)
}
func (W _xorm_io_xorm_EngineInterface) Iterate(a0 any, a1 xorm.IterFunc) error {
	return W.WIterate(a0, a1)
}
func (W _xorm_io_xorm_EngineInterface) Join(joinOperator string, tablename any, condition any, args ...any) *xorm.Session {
	return W.WJoin(joinOperator, tablename, condition, args...)
}
func (W _xorm_io_xorm_EngineInterface) Limit(a0 int, a1 ...int) *xorm.Session {
	return W.WLimit(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) MapCacher(a0 any, a1 caches.Cacher) error {
	return W.WMapCacher(a0, a1)
}
func (W _xorm_io_xorm_EngineInterface) MustCols(columns ...string) *xorm.Session {
	return W.WMustCols(columns...)
}
func (W _xorm_io_xorm_EngineInterface) NewSession() *xorm.Session {
	return W.WNewSession()
}
func (W _xorm_io_xorm_EngineInterface) NoAutoCondition(a0 ...bool) *xorm.Session {
	return W.WNoAutoCondition(a0...)
}
func (W _xorm_io_xorm_EngineInterface) NoAutoTime() *xorm.Session {
	return W.WNoAutoTime()
}
func (W _xorm_io_xorm_EngineInterface) NotIn(a0 string, a1 ...any) *xorm.Session {
	return W.WNotIn(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) Nullable(a0 ...string) *xorm.Session {
	return W.WNullable(a0...)
}
func (W _xorm_io_xorm_EngineInterface) Omit(columns ...string) *xorm.Session {
	return W.WOmit(columns...)
}
func (W _xorm_io_xorm_EngineInterface) OrderBy(order any, args ...any) *xorm.Session {
	return W.WOrderBy(order, args...)
}
func (W _xorm_io_xorm_EngineInterface) Ping() error {
	return W.WPing()
}
func (W _xorm_io_xorm_EngineInterface) Prepare() *xorm.Session {
	return W.WPrepare()
}
func (W _xorm_io_xorm_EngineInterface) Query(sqlOrArgs ...any) (resultsSlice []map[string][]byte, err error) {
	return W.WQuery(sqlOrArgs...)
}
func (W _xorm_io_xorm_EngineInterface) QueryInterface(sqlOrArgs ...any) ([]map[string]any, error) {
	return W.WQueryInterface(sqlOrArgs...)
}
func (W _xorm_io_xorm_EngineInterface) QueryString(sqlOrArgs ...any) ([]map[string]string, error) {
	return W.WQueryString(sqlOrArgs...)
}
func (W _xorm_io_xorm_EngineInterface) Quote(a0 string) string {
	return W.WQuote(a0)
}
func (W _xorm_io_xorm_EngineInterface) Rows(bean any) (*xorm.Rows, error) {
	return W.WRows(bean)
}
func (W _xorm_io_xorm_EngineInterface) SQL(a0 any, a1 ...any) *xorm.Session {
	return W.WSQL(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) Select(a0 string) *xorm.Session {
	return W.WSelect(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetCacher(a0 string, a1 caches.Cacher) {
	W.WSetCacher(a0, a1)
}
func (W _xorm_io_xorm_EngineInterface) SetColumnMapper(a0 names.Mapper) {
	W.WSetColumnMapper(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetConnMaxLifetime(a0 time.Duration) {
	W.WSetConnMaxLifetime(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetDefaultCacher(a0 caches.Cacher) {
	W.WSetDefaultCacher(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetExpr(a0 string, a1 any) *xorm.Session {
	return W.WSetExpr(a0, a1)
}
func (W _xorm_io_xorm_EngineInterface) SetLogLevel(a0 log.LogLevel) {
	W.WSetLogLevel(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetLogger(logger any) {
	W.WSetLogger(logger)
}
func (W _xorm_io_xorm_EngineInterface) SetMapper(a0 names.Mapper) {
	W.WSetMapper(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetMaxIdleConns(a0 int) {
	W.WSetMaxIdleConns(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetMaxOpenConns(a0 int) {
	W.WSetMaxOpenConns(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetQuotePolicy(a0 dialects.QuotePolicy) {
	W.WSetQuotePolicy(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetSchema(a0 string) {
	W.WSetSchema(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetTZDatabase(tz *time.Location) {
	W.WSetTZDatabase(tz)
}
func (W _xorm_io_xorm_EngineInterface) SetTZLocation(tz *time.Location) {
	W.WSetTZLocation(tz)
}
func (W _xorm_io_xorm_EngineInterface) SetTableMapper(a0 names.Mapper) {
	W.WSetTableMapper(a0)
}
func (W _xorm_io_xorm_EngineInterface) SetTagIdentifier(a0 string) {
	W.WSetTagIdentifier(a0)
}
func (W _xorm_io_xorm_EngineInterface) ShowSQL(show ...bool) {
	W.WShowSQL(show...)
}
func (W _xorm_io_xorm_EngineInterface) StoreEngine(storeEngine string) *xorm.Session {
	return W.WStoreEngine(storeEngine)
}
func (W _xorm_io_xorm_EngineInterface) Sum(bean any, colName string) (float64, error) {
	return W.WSum(bean, colName)
}
func (W _xorm_io_xorm_EngineInterface) SumInt(bean any, colName string) (int64, error) {
	return W.WSumInt(bean, colName)
}
func (W _xorm_io_xorm_EngineInterface) Sums(bean any, colNames ...string) ([]float64, error) {
	return W.WSums(bean, colNames...)
}
func (W _xorm_io_xorm_EngineInterface) SumsInt(bean any, colNames ...string) ([]int64, error) {
	return W.WSumsInt(bean, colNames...)
}
func (W _xorm_io_xorm_EngineInterface) Sync(a0 ...any) error {
	return W.WSync(a0...)
}
func (W _xorm_io_xorm_EngineInterface) Sync2(a0 ...any) error {
	return W.WSync2(a0...)
}
func (W _xorm_io_xorm_EngineInterface) SyncWithOptions(a0 xorm.SyncOptions, a1 ...any) (*xorm.SyncResult, error) {
	return W.WSyncWithOptions(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) Table(tableNameOrBean any) *xorm.Session {
	return W.WTable(tableNameOrBean)
}
func (W _xorm_io_xorm_EngineInterface) TableInfo(bean any) (*schemas.Table, error) {
	return W.WTableInfo(bean)
}
func (W _xorm_io_xorm_EngineInterface) TableName(a0 any, a1 ...bool) string {
	return W.WTableName(a0, a1...)
}
func (W _xorm_io_xorm_EngineInterface) Truncate(a0 ...any) (int64, error) {
	return W.WTruncate(a0...)
}
func (W _xorm_io_xorm_EngineInterface) UnMapType(a0 reflect.Type) {
	W.WUnMapType(a0)
}
func (W _xorm_io_xorm_EngineInterface) Unscoped() *xorm.Session {
	return W.WUnscoped()
}
func (W _xorm_io_xorm_EngineInterface) Update(bean any, condiBeans ...any) (int64, error) {
	return W.WUpdate(bean, condiBeans...)
}
func (W _xorm_io_xorm_EngineInterface) UseBool(a0 ...string) *xorm.Session {
	return W.WUseBool(a0...)
}
func (W _xorm_io_xorm_EngineInterface) Where(a0 any, a1 ...any) *xorm.Session {
	return W.WWhere(a0, a1...)
}

// _xorm_io_xorm_GroupPolicy is an interface wrapper for GroupPolicy type
type _xorm_io_xorm_GroupPolicy struct {
	IValue interface{}
	WSlave func(a0 *xorm.EngineGroup) *xorm.Engine
}

func (W _xorm_io_xorm_GroupPolicy) Slave(a0 *xorm.EngineGroup) *xorm.Engine {
	return W.WSlave(a0)
}

// _xorm_io_xorm_Interface is an interface wrapper for Interface type
type _xorm_io_xorm_Interface struct {
	IValue           interface{}
	WAlias           func(alias string) *xorm.Session
	WAllCols         func() *xorm.Session
	WAsc             func(colNames ...string) *xorm.Session
	WBufferSize      func(size int) *xorm.Session
	WCols            func(columns ...string) *xorm.Session
	WCount           func(a0 ...any) (int64, error)
	WCreateIndexes   func(bean any) error
	WCreateUniques   func(bean any) error
	WDecr            func(column string, arg ...any) *xorm.Session
	WDelete          func(a0 ...any) (int64, error)
	WDesc            func(a0 ...string) *xorm.Session
	WDistinct        func(columns ...string) *xorm.Session
	WDropIndexes     func(bean any) error
	WExec            func(sqlOrArgs ...any) (sql.Result, error)
	WExist           func(bean ...any) (bool, error)
	WFind            func(a0 any, a1 ...any) error
	WFindAndCount    func(a0 any, a1 ...any) (int64, error)
	WGet             func(a0 ...any) (bool, error)
	WGroupBy         func(keys string) *xorm.Session
	WID              func(a0 any) *xorm.Session
	WIn              func(a0 string, a1 ...any) *xorm.Session
	WIncr            func(column string, arg ...any) *xorm.Session
	WInsert          func(a0 ...any) (int64, error)
	WInsertOne       func(a0 any) (int64, error)
	WIsTableEmpty    func(bean any) (bool, error)
	WIsTableExist    func(beanOrTableName any) (bool, error)
	WIterate         func(a0 any, a1 xorm.IterFunc) error
	WJoin            func(joinOperator string, tablename any, condition any, args ...any) *xorm.Session
	WLimit           func(a0 int, a1 ...int) *xorm.Session
	WMustCols        func(columns ...string) *xorm.Session
	WNoAutoCondition func(a0 ...bool) *xorm.Session
	WNotIn           func(a0 string, a1 ...any) *xorm.Session
	WNullable        func(a0 ...string) *xorm.Session
	WOmit            func(columns ...string) *xorm.Session
	WOrderBy         func(order any, args ...any) *xorm.Session
	WPing            func() error
	WQuery           func(sqlOrArgs ...any) (resultsSlice []map[string][]byte, err error)
	WQueryInterface  func(sqlOrArgs ...any) ([]map[string]any, error)
	WQueryString     func(sqlOrArgs ...any) ([]map[string]string, error)
	WRows            func(bean any) (*xorm.Rows, error)
	WSQL             func(a0 any, a1 ...any) *xorm.Session
	WSelect          func(a0 string) *xorm.Session
	WSetExpr         func(a0 string, a1 any) *xorm.Session
	WSum             func(bean any, colName string) (float64, error)
	WSumInt          func(bean any, colName string) (int64, error)
	WSums            func(bean any, colNames ...string) ([]float64, error)
	WSumsInt         func(bean any, colNames ...string) ([]int64, error)
	WTable           func(tableNameOrBean any) *xorm.Session
	WTruncate        func(a0 ...any) (int64, error)
	WUnscoped        func() *xorm.Session
	WUpdate          func(bean any, condiBeans ...any) (int64, error)
	WUseBool         func(a0 ...string) *xorm.Session
	WWhere           func(a0 any, a1 ...any) *xorm.Session
}

func (W _xorm_io_xorm_Interface) Alias(alias string) *xorm.Session {
	return W.WAlias(alias)
}
func (W _xorm_io_xorm_Interface) AllCols() *xorm.Session {
	return W.WAllCols()
}
func (W _xorm_io_xorm_Interface) Asc(colNames ...string) *xorm.Session {
	return W.WAsc(colNames...)
}
func (W _xorm_io_xorm_Interface) BufferSize(size int) *xorm.Session {
	return W.WBufferSize(size)
}
func (W _xorm_io_xorm_Interface) Cols(columns ...string) *xorm.Session {
	return W.WCols(columns...)
}
func (W _xorm_io_xorm_Interface) Count(a0 ...any) (int64, error) {
	return W.WCount(a0...)
}
func (W _xorm_io_xorm_Interface) CreateIndexes(bean any) error {
	return W.WCreateIndexes(bean)
}
func (W _xorm_io_xorm_Interface) CreateUniques(bean any) error {
	return W.WCreateUniques(bean)
}
func (W _xorm_io_xorm_Interface) Decr(column string, arg ...any) *xorm.Session {
	return W.WDecr(column, arg...)
}
func (W _xorm_io_xorm_Interface) Delete(a0 ...any) (int64, error) {
	return W.WDelete(a0...)
}
func (W _xorm_io_xorm_Interface) Desc(a0 ...string) *xorm.Session {
	return W.WDesc(a0...)
}
func (W _xorm_io_xorm_Interface) Distinct(columns ...string) *xorm.Session {
	return W.WDistinct(columns...)
}
func (W _xorm_io_xorm_Interface) DropIndexes(bean any) error {
	return W.WDropIndexes(bean)
}
func (W _xorm_io_xorm_Interface) Exec(sqlOrArgs ...any) (sql.Result, error) {
	return W.WExec(sqlOrArgs...)
}
func (W _xorm_io_xorm_Interface) Exist(bean ...any) (bool, error) {
	return W.WExist(bean...)
}
func (W _xorm_io_xorm_Interface) Find(a0 any, a1 ...any) error {
	return W.WFind(a0, a1...)
}
func (W _xorm_io_xorm_Interface) FindAndCount(a0 any, a1 ...any) (int64, error) {
	return W.WFindAndCount(a0, a1...)
}
func (W _xorm_io_xorm_Interface) Get(a0 ...any) (bool, error) {
	return W.WGet(a0...)
}
func (W _xorm_io_xorm_Interface) GroupBy(keys string) *xorm.Session {
	return W.WGroupBy(keys)
}
func (W _xorm_io_xorm_Interface) ID(a0 any) *xorm.Session {
	return W.WID(a0)
}
func (W _xorm_io_xorm_Interface) In(a0 string, a1 ...any) *xorm.Session {
	return W.WIn(a0, a1...)
}
func (W _xorm_io_xorm_Interface) Incr(column string, arg ...any) *xorm.Session {
	return W.WIncr(column, arg...)
}
func (W _xorm_io_xorm_Interface) Insert(a0 ...any) (int64, error) {
	return W.WInsert(a0...)
}
func (W _xorm_io_xorm_Interface) InsertOne(a0 any) (int64, error) {
	return W.WInsertOne(a0)
}
func (W _xorm_io_xorm_Interface) IsTableEmpty(bean any) (bool, error) {
	return W.WIsTableEmpty(bean)
}
func (W _xorm_io_xorm_Interface) IsTableExist(beanOrTableName any) (bool, error) {
	return W.WIsTableExist(beanOrTableName)
}
func (W _xorm_io_xorm_Interface) Iterate(a0 any, a1 xorm.IterFunc) error {
	return W.WIterate(a0, a1)
}
func (W _xorm_io_xorm_Interface) Join(joinOperator string, tablename any, condition any, args ...any) *xorm.Session {
	return W.WJoin(joinOperator, tablename, condition, args...)
}
func (W _xorm_io_xorm_Interface) Limit(a0 int, a1 ...int) *xorm.Session {
	return W.WLimit(a0, a1...)
}
func (W _xorm_io_xorm_Interface) MustCols(columns ...string) *xorm.Session {
	return W.WMustCols(columns...)
}
func (W _xorm_io_xorm_Interface) NoAutoCondition(a0 ...bool) *xorm.Session {
	return W.WNoAutoCondition(a0...)
}
func (W _xorm_io_xorm_Interface) NotIn(a0 string, a1 ...any) *xorm.Session {
	return W.WNotIn(a0, a1...)
}
func (W _xorm_io_xorm_Interface) Nullable(a0 ...string) *xorm.Session {
	return W.WNullable(a0...)
}
func (W _xorm_io_xorm_Interface) Omit(columns ...string) *xorm.Session {
	return W.WOmit(columns...)
}
func (W _xorm_io_xorm_Interface) OrderBy(order any, args ...any) *xorm.Session {
	return W.WOrderBy(order, args...)
}
func (W _xorm_io_xorm_Interface) Ping() error {
	return W.WPing()
}
func (W _xorm_io_xorm_Interface) Query(sqlOrArgs ...any) (resultsSlice []map[string][]byte, err error) {
	return W.WQuery(sqlOrArgs...)
}
func (W _xorm_io_xorm_Interface) QueryInterface(sqlOrArgs ...any) ([]map[string]any, error) {
	return W.WQueryInterface(sqlOrArgs...)
}
func (W _xorm_io_xorm_Interface) QueryString(sqlOrArgs ...any) ([]map[string]string, error) {
	return W.WQueryString(sqlOrArgs...)
}
func (W _xorm_io_xorm_Interface) Rows(bean any) (*xorm.Rows, error) {
	return W.WRows(bean)
}
func (W _xorm_io_xorm_Interface) SQL(a0 any, a1 ...any) *xorm.Session {
	return W.WSQL(a0, a1...)
}
func (W _xorm_io_xorm_Interface) Select(a0 string) *xorm.Session {
	return W.WSelect(a0)
}
func (W _xorm_io_xorm_Interface) SetExpr(a0 string, a1 any) *xorm.Session {
	return W.WSetExpr(a0, a1)
}
func (W _xorm_io_xorm_Interface) Sum(bean any, colName string) (float64, error) {
	return W.WSum(bean, colName)
}
func (W _xorm_io_xorm_Interface) SumInt(bean any, colName string) (int64, error) {
	return W.WSumInt(bean, colName)
}
func (W _xorm_io_xorm_Interface) Sums(bean any, colNames ...string) ([]float64, error) {
	return W.WSums(bean, colNames...)
}
func (W _xorm_io_xorm_Interface) SumsInt(bean any, colNames ...string) ([]int64, error) {
	return W.WSumsInt(bean, colNames...)
}
func (W _xorm_io_xorm_Interface) Table(tableNameOrBean any) *xorm.Session {
	return W.WTable(tableNameOrBean)
}
func (W _xorm_io_xorm_Interface) Truncate(a0 ...any) (int64, error) {
	return W.WTruncate(a0...)
}
func (W _xorm_io_xorm_Interface) Unscoped() *xorm.Session {
	return W.WUnscoped()
}
func (W _xorm_io_xorm_Interface) Update(bean any, condiBeans ...any) (int64, error) {
	return W.WUpdate(bean, condiBeans...)
}
func (W _xorm_io_xorm_Interface) UseBool(a0 ...string) *xorm.Session {
	return W.WUseBool(a0...)
}
func (W _xorm_io_xorm_Interface) Where(a0 any, a1 ...any) *xorm.Session {
	return W.WWhere(a0, a1...)
}
