### Authorization by token, part 1. Retrieve and save token.
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "username": "user6",
  "password": "1234"
}

> {% client.global.set("auth_token", response.body.token); %}

### Register

POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "username": "user",
  "password": "1234",
  "email": "5@knt.li"
}

###
# Token test
POST http://localhost:8080/api/v1/tokenTest
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###
