# Get all lists
GET http://localhost:8080/api/v1/namespaces/1
Authorization: Bearer {{auth_token}}

###

# Get one list
GET http://localhost:8080/api/v1/lists/1172
Authorization: Bearer {{auth_token}}

###

# Add a new list
PUT http://localhost:8080/api/v1/namespaces/1/lists
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "test"
}

###

# Add a new item
PUT http://localhost:8080/api/v1/lists/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "text": "Task",
  "description": "Schinken"
}

###

# Delete a task from a list
DELETE http://localhost:8080/api/v1/lists/14
Authorization: Bearer {{auth_token}}

###

# Get all teams who have access to that list
GET http://localhost:8080/api/v1/lists/28/teams
Authorization: Bearer {{auth_token}}

###

# Give a team access to that list
PUT http://localhost:8080/api/v1/lists/1/teams
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"team_id":2, "right": 1}

###

# Update a teams access to that list
POST http://localhost:8080/api/v1/lists/1/teams/2
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"right": 0}

###

# Delete a team from a list
DELETE http://localhost:8080/api/v1/lists/10235/teams/1
Authorization: Bearer {{auth_token}}

###

# Delete a team from a list
DELETE http://localhost:8080/api/v1/lists/10235/teams/1
Authorization: Bearer {{auth_token}}

###

# Get all users who have access to that list
GET http://localhost:8080/api/v1/lists/28/users
Authorization: Bearer {{auth_token}}

###

# Give a user access to that list
PUT http://localhost:8080/api/v1/lists/1172/users
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"user_id":1, "right":1}

###

# Update a users access to that list
POST http://localhost:8080/api/v1/lists/30/users/3
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"right":2}

###

# Delete a user from a list
DELETE http://localhost:8080/api/v1/lists/28/users/3
Authorization: Bearer {{auth_token}}

###

# Get all pending tasks
GET http://localhost:8080/api/v1/tasks/all
Authorization: Bearer {{auth_token}}

###

# Get all pending tasks with priorities
GET http://localhost:8080/api/v1/tasks/all/desc
Authorization: Bearer {{auth_token}}

###

# Get all pending tasks in a range
GET http://localhost:8080/api/v1/tasks/all/dueadateasc/1546784000/1548784000
Authorization: Bearer {{auth_token}}

###

# Get all pending tasks in caldav
GET http://localhost:8080/api/v1/tasks/caldav
#Authorization: Bearer {{auth_token}}

###

# Update a task
POST http://localhost:8080/api/v1/tasks/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{"assignees":[
  {"id": 1}
]}

###

# Bulk update multiple tasks at once
POST http://localhost:8080/api/v1/tasks/bulk
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "task_ids": [3518,3519,3521],
  "text":"bulkupdated"
}

###
