
# Get all users
GET http://localhost:8080/api/v1/users
Authorization: Bearer {{auth_token}}

######
# Search for a user
GET http://localhost:8080/api/v1/users?s=3
Authorization: Bearer {{auth_token}}

###

## Update password

POST http://localhost:8080/api/v1/user/password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "old_password": "1234",
  "new_password": "1234"
}

###