// Vikunja is a to-do list application to facilitate your life.
// Copyright 2018-present Vikunja and contributors. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package yaegi

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"code.vikunja.io/api/pkg/log"
	"code.vikunja.io/api/pkg/plugins"
	"code.vikunja.io/api/pkg/yaegi_symbols"

	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
)

// dbPackagePath is the yaegi_symbols key for pkg/db, generated by `yaegi
// extract code.vikunja.io/api/pkg/db` (see vikunja_db.go's DO NOT EDIT header).
const dbPackagePath = "code.vikunja.io/api/pkg/db/db"

// unsafeForPlugins lists db symbols that yaegi extract mechanically included
// but that only make sense for the Go test harness or a validated CLI restore
// flow (db.WipeEverything's one real caller, pkg/modules/dump/restore.go),
// never for interpreted plugin code: WipeEverything drops every application
// table with no confirmation, dry-run, or audit hook. No shipped plugin or
// yaegi test references any of these (verified: examples/plugins/example and
// every pkg/plugins/yaegi/*_test.go), so removing them from what plugins can
// resolve changes no working behavior.
var unsafeForPlugins = []string{
	"WipeEverything",
	"Dump",
	"Restore",
	"RestoreAndTruncate",
	"CreateTestEngine",
	"InitFixtures",
	"InitTestFixtures",
	"LoadFixtures",
	"LoadAndAssertFixtures",
}

// pluginSafeSymbols returns yaegi_symbols.Symbols with unsafeForPlugins
// stripped from the pkg/db entry, leaving the shared generated map untouched.
func pluginSafeSymbols() map[string]map[string]reflect.Value {
	filtered := make(map[string]map[string]reflect.Value, len(yaegi_symbols.Symbols))
	for pkg, symbols := range yaegi_symbols.Symbols {
		filtered[pkg] = symbols
	}

	dbSymbols := make(map[string]reflect.Value, len(yaegi_symbols.Symbols[dbPackagePath]))
	for name, v := range yaegi_symbols.Symbols[dbPackagePath] {
		dbSymbols[name] = v
	}
	for _, name := range unsafeForPlugins {
		delete(dbSymbols, name)
	}
	filtered[dbPackagePath] = dbSymbols

	return filtered
}

func init() {
	plugins.YaegiPluginLoader = LoadPluginFull
}

// LoadPlugin loads a plugin from a directory of Go source files using the Yaegi interpreter.
func LoadPlugin(dir string) (plugins.Plugin, error) {
	loaded, err := LoadPluginFull(dir)
	if err != nil {
		return nil, err
	}
	return loaded.Plugin, nil
}

// LoadPluginFull loads a plugin and all its optional capabilities via typed factory functions.
//
// Because Yaegi wraps interpreted values per return type, sub-interface type assertions
// (e.g. Plugin -> AuthenticatedRouterPlugin) do not work. Instead, plugins must export
// typed factory functions for each capability they implement:
//
//   - NewPlugin() plugins.Plugin                                          (required)
//   - NewAuthenticatedRouterPlugin() plugins.AuthenticatedRouterPlugin    (optional)
//   - NewUnauthenticatedRouterPlugin() plugins.UnauthenticatedRouterPlugin (optional)
//   - NewMigrationPlugin() plugins.MigrationPlugin                        (optional)
func LoadPluginFull(dir string) (*plugins.LoadedYaegiPlugin, error) {
	// yaegi's stdlib.Symbols grants full OS-level access (file read/write/
	// delete, process spawning, env vars, raw sockets) and the vikunja
	// symbols below grant a raw, unscoped DB session - a loaded plugin runs
	// as a fully-trusted extension with the server process's own privileges,
	// not a sandboxed third-party runtime. Only load plugin source you wrote
	// or fully trust.
	log.Warningf("Loading yaegi plugin from %s - plugin code runs with the server process's full OS and database privileges", dir)

	i := interp.New(interp.Options{})
	if err := i.Use(stdlib.Symbols); err != nil {
		return nil, fmt.Errorf("loading stdlib symbols: %w", err)
	}
	if err := i.Use(pluginSafeSymbols()); err != nil {
		return nil, fmt.Errorf("loading vikunja symbols: %w", err)
	}

	// Read and evaluate all .go files in the plugin directory.
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("reading plugin dir %s: %w", dir, err)
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		src, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", e.Name(), err)
		}
		if _, err = i.Eval(string(src)); err != nil {
			return nil, fmt.Errorf("evaluating %s: %w", e.Name(), err)
		}
	}

	loaded := &plugins.LoadedYaegiPlugin{}

	// Required: NewPlugin
	v, err := i.Eval("main.NewPlugin")
	if err != nil {
		return nil, fmt.Errorf("looking up NewPlugin: %w", err)
	}
	newPlugin, ok := v.Interface().(func() plugins.Plugin)
	if !ok {
		return nil, fmt.Errorf("NewPlugin has wrong signature: %T", v.Interface())
	}
	loaded.Plugin = newPlugin()

	// Optional: NewAuthenticatedRouterPlugin
	if v, err := i.Eval("main.NewAuthenticatedRouterPlugin"); err == nil {
		if fn, ok := v.Interface().(func() plugins.AuthenticatedRouterPlugin); ok {
			loaded.AuthRouter = fn()
		}
	}

	// Optional: NewUnauthenticatedRouterPlugin
	if v, err := i.Eval("main.NewUnauthenticatedRouterPlugin"); err == nil {
		if fn, ok := v.Interface().(func() plugins.UnauthenticatedRouterPlugin); ok {
			loaded.UnauthRouter = fn()
		}
	}

	// Optional: NewMigrationPlugin
	if v, err := i.Eval("main.NewMigrationPlugin"); err == nil {
		if fn, ok := v.Interface().(func() plugins.MigrationPlugin); ok {
			loaded.Migration = fn()
		}
	}

	return loaded, nil
}
